### ISSUE TITLE
grouping for inscriptions and papyri

### ISSUE THREAD

**Issue by PietroLiuzzo** [distributed-text-services/specifications#10]
For inscriptions at least I believe there could be benefit in being able to query using a concept of "region" for TextGroups, so that I might do for example 

dts/eagle 

and get all eagle collections listed, so that I can for example do

dts/{dts-ns}/{text-group}/{work}/{edition}
dts/eagle/irt/irt957

but I could also do

dts/africaProconsularis/irt957

to get to that inscription

or 

dts/africaProconsularis

 to get a list of results (version) with that provenance

I would then get the same result querying for

dts/{textgroup}/{work}
dts/eagle/tm203114

or

dts/{region}/{work}
dts/africaProconsularis/tm203114

and then perhaps go down to the line of each specific edition of that

dts/{region}/{work}/{edition}/text
dts/africaProconsulari/tm203113/HD059795/1 to get Imp(eratori) Caes(ari) 

as I would do from an edition point of view quering for

dts/{dts-ns}/{textGroup}/{work}/{edition}/text
dts/eagle/irt/tm203113/irt957/1 to get nothing as there is no text recorded in this edition for this milestone (picked the first... not very good example...)

**Comment by PonteIneptique** [comment]
For cleaning reason, we are closing old issues.
Please feel free to comment if you think we should reopen.
