### ISSUE TITLE
decide upon how to handle navigation for document endpoint

### ISSUE THREAD

**Issue by balmas** [distributed-text-services/specifications#102]
we were using link headers for collection and navigation endpoints but per #98 we have decided to prefer the hydra link properties in the json response. we need to decide how to handle this for the document endpoint which returns xml.

**Comment by hcayless** [comment]
From discussion on Jul. 19 (see https://www.iana.org/assignments/link-relations/link-relations.xhtml):

prev, next, up -> Document pages
contents -> Navigation API
collection -> Collection Endpoint
first, last  -> Document pages

**Comment by PonteIneptique** [comment]
Fixed in #115
