### ISSUE TITLE
start and end consistency

### ISSUE THREAD

**Issue by hcayless** [distributed-text-services/specifications#106]
In the Navigation API, the start and end params are treated as milestones between which the range of references to be retrieved exist (`start=1, end=3` returns the ref "2"), but in the Document API, they are inclusive (`start=1, end=3` returns sections 1, 2, and 3). I find this confusing and it makes me wonder how to deal with things at the edges. If I want refs from books 1-2 would I need to give `start=0, end=3`? Wouldn't it be better to treat them consistently as inclusive?

**Comment by PonteIneptique** [comment]
Hey,
I think the example is not the best, as for this one you would have to only do `passage=1`.
But you're right, start and end should be inclusive.

**Comment by hcayless** [comment]
Yeah, I realized that after I posted it, so I changed my example to a range. If there are no objections then, I'll change the wording and close this issue.

**Comment by PonteIneptique** [comment]
Maybe a PR that we would confirm tomorrow would be the best? I love PR for this kind of things :)
