### ISSUE TITLE
my texts are not in your canon...

### ISSUE THREAD

**Issue by PietroLiuzzo** [distributed-text-services/specifications#11]
https://github.com/distributed-text-services/API/blob/master/userstories.csv#L25

https://github.com/distributed-text-services/API/blob/master/userstories.csv#L26

https://github.com/distributed-text-services/API/blob/master/userstories.csv#L27

My corpus is made mainly of literary texts which have a canonical reference. let's say they are biblical works. For this I could use the tlg ids and then add a translation or a different edition. how?

But I have also texts which I am publishing which are not in any canon, authors which are not listed anywhere and I want to "canonicize" them and make the resources I have available via the DTS service, what do I do?

**Comment by PonteIneptique** [comment]
I am not sure this is a User Story in the same way of the other. This is indeed a good question through : @PietroLiuzzo would you accept a new title "Choose an identifier for a new text" ?

**Comment by PietroLiuzzo** [comment]
yes, perhaps it does need splitting as well. 
1. I want to find out what the identifier is
2. I want to "register" a text which is not in the list with an identifier which I decide. This would fit with yoru title.

**Comment by balmas** [comment]
I think this is met as the API doesn't present restrictions on identifier. @PietroLiuzzo can you confirm?

**Comment by PonteIneptique** [comment]
For cleaning reason, we are closing old issues.
Please feel free to comment if you think we should reopen.
