### ISSUE TITLE
[Meta] Clean up of issues

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#111]
I'd like to do some clean up in the issues : I propose the following to be closed (because they are not relevant to our current workflow. Their content will still be available...) : 

- https://github.com/distributed-text-services/specifications/issues/2
- https://github.com/distributed-text-services/specifications/issues/3
- https://github.com/distributed-text-services/specifications/issues/4
- https://github.com/distributed-text-services/specifications/issues/5
- https://github.com/distributed-text-services/specifications/issues/6
- https://github.com/distributed-text-services/specifications/issues/7
- https://github.com/distributed-text-services/specifications/issues/8
- https://github.com/distributed-text-services/specifications/issues/9
- https://github.com/distributed-text-services/specifications/issues/10
- https://github.com/distributed-text-services/specifications/issues/11
- https://github.com/distributed-text-services/specifications/issues/12 (Actually this one is fixed)
- https://github.com/distributed-text-services/specifications/issues/15
- https://github.com/distributed-text-services/specifications/issues/16
- https://github.com/distributed-text-services/specifications/issues/17
- https://github.com/distributed-text-services/specifications/issues/20
- https://github.com/distributed-text-services/specifications/issues/24 (fixed by dc:metadata)
- https://github.com/distributed-text-services/specifications/issues/26
- https://github.com/distributed-text-services/specifications/issues/27
- https://github.com/distributed-text-services/specifications/issues/30
- https://github.com/distributed-text-services/specifications/issues/31
- https://github.com/distributed-text-services/specifications/issues/32 (Irrelevant with current choices for the moment)

So in general User Stories or things that were fixed

**Comment by balmas** [comment]
I don't object to closing these but I think as we do so we should add comments which state explicitly the reason why. Some of these were determined to be out of scope, but others were actually implemented in some way in the specification. It would be good to be clear about which is which.
