### ISSUE TITLE
Change `chunkSize` into `rangeSize`

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#113]
In our documentation, we are talking about range. And I always felt `chunkSize` was weird : we rarely talk about range when talking about range of references. I would like to reopen this question if you are okay with it.

Link : https://github.com/distributed-text-services/specifications/blob/master/Navigation-Endpoint.md#query-parameters

**Comment by balmas** [comment]
I have no objections to using rangeSize instead of chunkSize. Maybe groupSize is better though?

**Comment by PonteIneptique** [comment]
Damn we did not address that today

**Comment by mromanello** [comment]
I agree with @balmas: to me, `groupSize` feels more appropriate as a range is typically defined by start/end, while to define a group is enough to specify its size.

**Comment by PonteIneptique** [comment]
Damn, I just figured I put it as `groupBy` in the Capitains implementation. Should we move to `groupSize` or `groupBy` ? 
I feel like `groupBy` carries the sense that it is built by the service, while `groupSize` could feel like a *filter*.

**Comment by balmas** [comment]
`groupBy` is fine with me

**Comment by PonteIneptique** [comment]
Closed by https://github.com/distributed-text-services/specifications/commit/431ce7ad67109e63908e8b4e27604a68f3aa3895
