### ISSUE TITLE
we should support a response that includes just TEI

### ISSUE THREAD

**Issue by balmas** [distributed-text-services/specifications#12]
for simplicity of integration with linked data environments (e.g. such as the EAGLE Storytelling app) it would be good to support an option which returns a passage of text as pure, fully formatted, TEI (including header) with no wrapper.

**Comment by jonathanrobie** [comment]
I wonder if we should have a way to include links in such a response, e.g. next page etc.  Perhaps with processing instructions?

 <?xml-stylesheet type="text/tei+xml" rel="prev" href="page4.tei"?> 
 <?xml-stylesheet type="text/tei+xml" rel="next" href="page6.tei"?> 

XML text is mainstream for us, wrapping it causes problems, but putting links in processing instructions makes them easy to ignore.  We should also ask the TEI folks if they have a convention like this.

**Comment by balmas** [comment]
This is a requirement for the passage API. Will reopen there.

**Comment by PonteIneptique** [comment]
This issue has been dealt with and is covered in TEI.
