### ISSUE TITLE
nav=parent or nav=parents

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#123]
In Collection-Endpoint.md, we have `parent` in the list of parameters but `parent` in the example, which one should it be ?

`parents`: https://github.com/distributed-text-services/specifications/blob/master/Collection-Endpoint.md#query-parameters
`parent`: https://github.com/distributed-text-services/specifications/blob/master/Collection-Endpoint.md#querying-parents

**Comment by balmas** [comment]
I think we support the concept of multiple parents for a collection, right? If so, then my vote is for `parents` plural.
