### ISSUE TITLE
Is it volontary that start, end and ref are in the Hydra namespace ?

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#124]
Dear all,
looking at https://github.com/distributed-text-services/specifications/blob/master/Navigation-Endpoint.md#response it seems that `ref`, `start` and `end` are in the hydra Namespace. It feels like a mistake. 

Any idea on the matter ?

**Comment by balmas** [comment]
I think they should be in the dts namespace

**Comment by architexte** [comment]
Agree. It has to be in the DTS NS. By the way, there is non `ref`, `start` or `end` [hydra properties](https://www.hydra-cg.com/spec/latest/core/#properties).

**Comment by balmas** [comment]
voted to accept by the technical committee on 11-Oct-2019

**Comment by jonathanrobie** [comment]
We agreed that these belong in DTS.
