### ISSUE TITLE
Clean up documentation examples names

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#125]
Our example names are sometime really bad (I know, I wrote most of them ;)) and could be shortened.

Can anyone take this task ?

**Comment by balmas** [comment]
which names do you mean, @PonteIneptique ? Names of collections and member items? Or the examples themselves (e.g. "Sub-collection, not readable but small") ?

**Comment by PonteIneptique** [comment]
`Sub-collection, not readable but small`

**Comment by balmas** [comment]
Ok, I made an attempt. See #132

**Comment by PonteIneptique** [comment]
Closed then :)
