### ISSUE TITLE
Ability to explicit precision of excerpt in dts:wrapper

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#133]
Placeholder to finish when I have power (emylonas)

**Comment by PonteIneptique** [comment]
Ok, so directly after the DTS presentation at TEI, @emylonas discussed with me issues for them if they were to implement.

In order to not have to work on completely new software that would need to parse in-between milestones and reconstruct whole xpaths, the question was if we could have a way to indicate the precision of the passage response.

One way would be to propose : `<dts:fragment unprecise="true">...</dts:fragment>` ?

**Comment by balmas** [comment]
hmm. so what does this mean? That the requested passage is somewhere within the supplied fragment?

**Comment by emmamorlock** [comment]
that seems very interesting for the corpuses with milestones (as <l> is not a just a line of text but more a line of verse, in the epigraphic corpuses the most common situation is a line between two <lb/> milestones. 
But "unprecise='true' seems" very... unprecise, compare to what the different things that can be expressed... could we ask Elli for a use case? or could you describe with more detail what you understand of your use case? thanks

**Comment by PonteIneptique** [comment]
I think it would be good if @emylonas would provide her own use case.

What I also know is that I don't want us to reinvent TEI and a simple binary attribute would do it hopefully.

**Comment by emylonas** [comment]
Hi all - what came to mind when @PonteIneptique was presenting is the situation where there the referencing system in place is a set of milestones arbitrarily placed in the text. Something like Stephanus pages, or perhaps sentence or sense delimiters. I have an early modern book right now where we have put in markers at approx. sentence ends (sometimes more than 1 sentence if they are closely related) in the original Latin, but are carrying these over to the English translation, where they are even more arbitrary. What is the retrieved fragment in this case? starting point milestone until the next one? Certain amount of words on either side of the milestone? If we are dealing with lines of verse, for ex. this is easy, you get the container element indicated by the reference. But what comes back when there is no container and how is it determined? I think that I should perhaps have seen this in @PonteIneptique's demo, but don't feel that I have a good grasp. 

Ex: 

<p>
<milestone n="1"/>One sentence here, let's say that it's a long one. And a little following one.<milestone n="2"/> Here's another sentence but it is very long and has two points in it;<milestone n="3"/> and some more words to follow.<milestone n="4"/>
</p>

Assuming that those sentences are much longer, what fragment does one get back when asking for a milestone? 

Or I'm missing something completely?

**Comment by PietroLiuzzo** [comment]
We also have several kinds of text structuring elements. Sometimes we have
both l lb and pb of different editions. I actually make decisions in the
implementation about what the canonical reference structure refers to. So
if it is a manuscript I take the pb and the citation structure will take an
inclusive range i.e. 1ra-2vb will take everything until pb 3r.

If it is Exodus 1,3-2,1 for example I look at chapters and lines and take
each line in the range and ignore eventually present pb etc because the
citation structure is chapter, verse.

My take would be that you would have to decide what the citation structure
declared resolves to in your xml

Elli Mylonas <notifications@github.com> schrieb am Di., 18. Sep. 2018,
18:47:

**Comment by balmas** [comment]
So it sounds like I there are 2 parts to this: an editorial decision and an ability to specify the nature of the decision to the consumers. 

I agree with Pietro that it should be up to the publisher of a text to define the reference units and what they return. But if it is not technically possible to restrict what is returned to only the specific text reference requested, it seems like it would be good to have a way to inform the client about that.

**Comment by PietroLiuzzo** [comment]
#110

**Comment by balmas** [comment]
Reading this again (from the perspective of the client) I agree this would be really good to support,

**Comment by PonteIneptique** [comment]
During the RC Workshop in Duke, `dts:wrapper` has been given three attributes, `@start`, `@ref`, and `@end`, which can provide XPath to the node being identified by `?ref`, `?start`/`?end` in case they are used. 

The commit can be found in https://github.com/monotasker/specifications/commit/3a8762f5fdab5a857eb7bd1501227b87c4044385
