### ISSUE TITLE
Collection should have a parentNumber and a childrenNumber

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#141]
*Before diving into the issue, I must note it might have been something we dismissed earlier in meetings, but I feel it's good to at least write down why we dismissed it*

Currently, Collection have their `totalItems` property. It's really useful, except it's tied to the navigation sense (you go top to bottom, you get children number, you go bottom to top, you get parents number).

This means that navigating down, like : 

0. *`Collection Name [Children Collection]`*
1. General Collection [Latin, Epistolary, Greek]
2. Latin [ Cicero's Letters, Cicero's De finibus]
3. Cicero's Letters

We have no easy way to be sure that `Cicero's Letters` has two parents, except querying it. Hence I think at least displaying the number of parents and children would allow for not making unnecessary queries.

**Comment by balmas** [comment]
What are the use cases for knowing the number of parents?

**Comment by PonteIneptique** [comment]
1. When I want all metadata about one document, not having to do a
?nav=children and ?nav=parent
2. When browsing bottom-down, how do I know item X does not have more than
one parent without requiring to do 1. ?

Le jeu. 1 nov. 2018 à 14:58, Bridget Almas <notifications@github.com> a
écrit :

**Comment by emmamorlock** [comment]
Isn't the solution linked to having some kind of indexation when the branches are created. You don't do a query, you check the index... ?

**Comment by PonteIneptique** [comment]
I am not sure I understand what you mean, and given that @balmas needed more clarity, here is a situation:

Let's say you want information about `urn:cts:latinLit:phi1103.phi001.lascivaroma-lat1`

Right now, what you'd get is:
```json
{
    "@context": {
        "@vocab": "https://www.w3.org/ns/hydra/core#",
        "dc": "http://purl.org/dc/terms/",
        "dts": "https://w3id.org/dts/api#"
    },
    "@id": "urn:cts:latinLit:phi1103.phi001.lascivaroma-lat1",
    "@type" : "Resource",
    "title" : "Priapeia",
    "description": "Priapeia based on the edition of Aemilius Baehrens",
    "totalItems": 0,
    "dts:dublincore": {
        "dc:title": [{"@language": "la", "@value": "Priapeia"}],
        "dc:description": [{
           "@language": "en",
            "@value": "Anonymous lascivious Poems "
        }],
        "dc:type": [
            "http://chs.harvard.edu/xmlns/cts#edition",
            "dc:Text"
        ],
        "dc:source": ["https://archive.org/details/poetaelatinimino12baeh2"],
        "dc:dateCopyrighted": 1879,
        "dc:creator": [
            {"@language": "en", "@value": "Anonymous"}
        ],
        "dc:contributor": ["Aemilius Baehrens"],
        "dc:language": ["la", "en"]
    },
    "dts:passage": "/api/dts/documents?id=urn:cts:latinLit:phi1103.phi001.lascivaroma-lat1",
    "dts:references": "/api/dts/navigation?id=urn:cts:latinLit:phi1103.phi001.lascivaroma-lat1",
    "dts:download": "https://raw.githubusercontent.com/lascivaroma/priapeia/master/data/phi1103/phi001/phi1103.phi001.lascivaroma-lat1.xml",
    "dts:citeDepth": 2, 
    "dts:citeStructure": [
        {
            "dts:citeType": "poem",
            "dts:citeStructure": [
                {
                    "dts:citeType": "line"
                }
            ]
        }
    ]
}
```

The `totalItems` property is tied to the value of the query parameter `?nav`, which, by default, is `children`. Retrieving this collection metadata, I know for a fact that this collection has no children.
**But**, there is no way to know how many parents it has, except for querying with `?nav=parents`.

`totalItems` is a pagination information to some extent: it tells you, in a view, how many of the current type of item (children or parent) there is. It would be good to have both other numbers (children and parents) to avoid doubling querying. 

Here:

```json
{
    "@id": "urn:cts:latinLit:phi1103.phi001.lascivaroma-lat1",
    "@type" : "Resource",
    "title" : "Priapeia",
    "description": "Priapeia based on the edition of Aemilius Baehrens",
    "totalItems": 0,
    "totalChildren": 0,
    "totalParents": 1,
}
```

That's the most important use case. The other use case is obviously that our collection are not necessarily in a tree model: one collection can have multiple parents. If we were to browse from the root collection to one item that has two parents, we would completely not see it, because I doubt we are gonna query `?nav=parents` for every collections.

I hope this is clearer

**Comment by balmas** [comment]
I can see that it is useful to know whether an item has *any* parents or *any* children. And given that that metadata would be useful, although I am still not sure why the number of parents or children is important, I can't see any harm in providing it rather than making that a boolean property.

**Comment by PietroLiuzzo** [comment]
+1 to providing this value

**Comment by architexte** [comment]
In your last example @PonteIneptique, I don't understand the introduction of the new `totalChildren` prop, as we already have the `totalItems` prop which is [well defined](https://github.com/distributed-text-services/specifications/blob/master/Collections-Endpoint.md#scheme).

**Comment by PonteIneptique** [comment]
@architexte The issue of totalItems is that it is dependant on the nav parameters, it does not necessarly holds the children count :/

**Comment by emmamorlock** [comment]
Thanks for the clarification. I admit my remark was not relevant in that context. Let me ask to know more about your use case. You make it clear that with that property we can differentiate between an item in a tree structure (only one parent) and an item in a graph structure (2 or more parents). Could you elaborate more on what use you would do with that information? Once you know an item has 4 parents, what kind of "pagination" do you produce (sorry if the question misses the point)...

**Comment by PonteIneptique** [comment]
@emmamorlock Let's imagine a client app, solely based on the data from a DTS API. We browse the collection top down. If we have 3 parents shown in the item, the application knows it should query with "?nav=parents" to give this information to the enduser (parents which will be shown in the property dts:members). But, if it has only 1 parent, it won't need this secondary query (because we came from it, it had the ability to cache it most probably)

**Comment by emmamorlock** [comment]
Ok I get it. It's not the total number of parents that is used, and it's just a "browse/don't browse" situation. Thanks!
I also think it's useful.

**Comment by balmas** [comment]
clarifications from technical committee meeting

totalChildren - total number of members that you will find if you do nav=children
totalParents - total number of members that you will find if you do nav=parents
totalItems - total number of items that you can find in members

**Comment by balmas** [comment]
technical committee voted to accept on 11-Oct-2019

**Comment by balmas** [comment]
See also note in https://github.com/distributed-text-services/specifications/issues/163#issuecomment-543896066 about need for clarification of totalItems

**Comment by jonathanrobie** [comment]
Closing.  The pull request will be merged.
