### ISSUE TITLE
Write the supported language for support

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#143]
I open this new discussion here because I think it's important to make it public although it is not strictly about the specs.

One of the issues I have faced with many users (regarding my own repos) is their fear to post in English when it was not their native language. I feel like one way to make "asking questions in non-English language"  easier would be to show which language is accepted in issues (have a nice set of languages written at the *front page*, I thought about flags but then the choice of a flag for a specific language could also be politically complicated.).

I also see one counterargument about this : by showing language we support, we also exclude languages we can't. Hence I think this needs discussion.

**Comment by PietroLiuzzo** [comment]
perhaps is just about how we phrase it? 
like instead of "accepted languages", list languages which people on the list read and write in, so that people know what languages they can write in to be understood? a count of how many people read/write each language might also help?

**Comment by PietroLiuzzo** [comment]
ma in pratica cosa succede se davvero scrivo non in inglese?

**Comment by PietroLiuzzo** [comment]
übersetzt dann man meine frage für die interessierte Teilnehmer?

**Comment by balmas** [comment]
> perhaps is just about how we phrase it?
> like instead of "accepted languages", list languages which people on the list read and write in, so that people know what languages they can write in to be understood? a count of how many people read/write each language might also help?

I really like this suggestion.

**Comment by mromanello** [comment]
also, once we have identified *which* languages people in the community *can* speak (and thus support) one may think of offering a summary/translation in each of those languages for each issue – although I fear this may have a certain overhead. But definitely it would make the community more welcoming/inclusive.

**Comment by kmpenner** [comment]
What do you think about this proposal: anyone can write in any language. I imagine many of us here are like me in that we can understand multiple languages but we don’t  feel comfortable writing in them.

**Comment by PonteIneptique** [comment]
@kmpenner I think anyone can write in any language, but it needs to be stated somehow. Inclusivity on this front needs to be achieved :) A nice way to say that would be to say that in multiple languages ;)
