### ISSUE TITLE
"Entry Point" document is too much of a "we did not know where to put it" page

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#149]
Currently, the Entry Point holds information about : 

- The Entry Point
- The Error Messages
- Media Types
- Discussion about the depth of `dts:extensions` and `dts:dublincore`
- Status Code
- Vocabulary

I would propose to split this another way : 

- Entry Point page
- Errors messages, Status codes and Media Types
- "Ontology" (In place of a better name)
- FAQ

**Comment by PonteIneptique** [comment]
Link : https://distributed-text-services.github.io/specifications/Entry.html

**Comment by monotasker** [comment]
We published the resolution of this issue during the tech committee meeting on 2024-03-08. The documentation was reorganized to combine the three endpoints in a single page, with explanations and definitions applying to all three at the top of the documentation.

commit https://github.com/distributed-text-services/specifications/commit/a0db8ca0f5b9ef2e208baae7cacd8e2b6108685b
release https://github.com/distributed-text-services/specifications/releases/tag/1-alpha1

This is an alpha release and we are looking for feedback!
