### ISSUE TITLE
Terminology: Need a Glossary

### ISSUE THREAD

**Issue by jonathanrobie** [distributed-text-services/specifications#15]
We need a glossary to help us speak about the API more clearly.  We have more than one rival set of technical vocabulary, and some of the terms in our vocabularies are at odds with the way they are used in computer science as a whole (e.g. 'namespace', 'version').

Notes from today's meeting:

**Levels and vocabulary**
- CTS Hierarchy : Namespace -> Textgroup > Work > Version > Passage
- CTS Namespace : first part of a cts URN, is a default collection, eg. greekLit, latinlit
- CTS Textgroup : Highest common available for a set of texts, ie. author identifier, place where papyrii have been found, etc.
- CTS Work : Expression of a text (Illiad of Homer)
- CTS Version : Manifestion of a text ( Budé edition of Homer's Illiad  )
- CTS Passage : A text chunk of a Version
- CTS Inventory : Collection of version and their parent metadata

**Rival FRBR Terminology**
- CTS TextGroup = FRBR WorkGroup 
- CTS Work = FRBR Work = "Work is a "distinct intellectual or artistic creation." For example, Beethoven's Ninth Symphony apart from all ways of expressing it is a work. When we say, "Beethoven's Ninth is magnificent!" we generally are referring to the work.
- CTS Version = FRBR Expression = "is "the specific intellectual or artistic form that a work takes each time it is 'realized.'"[1] An expression of Beethoven's Ninth might be each draft of the musical score he writes down (not the paper itself, but the music thereby expressed)."
  I REALLY disagree about the Version=Expression equivalence: There can be several version of a particular expression. Many different editors can produce a version of a particular expression of a work
  For example, several editors could produce different editions of a particular "draft" of Beethoven's 9th symphony.
- CTS ??? = FRBR Manifestation = "the physical embodiment of an expression of a work. As an entity, manifestation represents all the physical objects that bear the same characteristics, in respect to both intellectual content and physical form."
- CTS Exemplar = FRBR Item (a single book in a single library of a particular Manifestation) = "Item is "a single exemplar of a manifestation."

**Rival FRBR Terminology proposed by Jeff**
- CTS TextGroup = FRBR WorkGroup 
- CTS ??? = FRBR Work = "Work is a "distinct intellectual or artistic creation." For example, Beethoven's Ninth Symphony apart from all ways of expressing it is a work. When we say, "Beethoven's Ninth is magnificent!" we generally are referring to the work. [HAC: I think CTS Work is a FRBR Work, but it confuses the issue by short-circuiting references to the work to a default instantiation] [JW: if that's true, then maybe there is no corresponding term at the FRBR expression level. But either way I think that "short-circuiting" is a problem that needs to be addressed.] 
- CTS Work = FRBR Expression = "is "the specific intellectual or artistic form that a work takes each time it is 'realized.'"[1] An expression of Beethoven's Ninth might be each draft of the musical score he writes down (not the paper itself, but the music thereby expressed)."
- CTS Version = FRBR Manifestation = "the physical embodiment of an expression of a work. As an entity, manifestation represents all the physical objects that bear the same characteristics, in respect to both intellectual content and physical form."
- CTS Exemplar = FRBR Item (a single book in a single library of a particular Manifestation) = "Item is "a single exemplar of a manifestation."

**Comment by emmamorlock** [comment]
There's a documentation of the CTS with FRBR is documented on the [Cite github pages here]http://cite-architecture.github.io/ctsurn/overview/). Doesn't seem to leave much part to interpretation or disagreement.
It seems to me that "version" in the CTS terminology is something specific. Not "any particular form" but particular forms which correspond to a set of rules or conventions like : an edition, a translation, what CTS calls a "notional work".
It seem to me that the CTS model skips the FRBR manifestation level, willingly. (

> The CTS URN’s version corresponds to the “expression” in the FRBR model, while exemplars correspond to “items” in FRBR parlance. At the “version” level, a text may be an “edition” of the notional “work”, that is, a version of the work in the language in which the work was originally composed. A version in any other language is a translation. The CTS URN does not distinguish between editions and translation; they are both expressed by version-level URNs.

> A version identifier may be followed by an identifier for a specific exemplar of the version, corresponding to the item level of FRBR. (Note that there is no level of a CTS URN correponding to the FRBR manifestation.) [http://www.homermultitext.org/hmt-docs/specifications/ctsurn/specification.html]

As I understand it, the alignment is between CTS and FRBR is:
- TextGroup == no FRBR entity, no semantic 
    "Text groups have no direct parallel in FRBR" says the CTS doc, and I haven't found either the entity WorkGroup in the FRBR model)
- CTS Work == FRBR Work ("notional work") "an abstract idea of the content expressed in all versions of a work, in the original language or in translation").
- CTS version (edition or translation) == FRBR expression
- CTS exemplar == FRBR item

_Hope it helps!_

**Comment by jeffreycwitt** [comment]
Very helpful. 

I still wonder why FRBR Manifestation was left out. See https://github.com/distributed-text-services/API/issues/18

**Comment by balmas** [comment]
see  https://docs.google.com/spreadsheets/d/1eHH6Pk9TX_p9GaTYfJWyiJz0znovk8iDI8IknmTEhIQ/edit?usp=sharing for a start

**Comment by PonteIneptique** [comment]
I think we should have a document in this repo if we all agree on this document.

**Comment by PonteIneptique** [comment]
For cleaning reason, we are closing old issues.
Please feel free to comment if you think we should reopen.
