### ISSUE TITLE
Take down the main github.io site or have a redirection

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#150]
Right now, the main https://distributed-text-services.github.io/ site is a partial and old copy of https://distributed-text-services.github.io/specifications
As much as I love w3id.org, I have already seen people not caring about the PURL and deciding to only cite or use the github one. Having two might lead to issues.

**Comment by jonathanrobie** [comment]
We shouldn't have two.

I don't think PURLs are being used at all.

**Comment by PonteIneptique** [comment]
Done.
