### ISSUE TITLE
Important past conversations

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#152]
This is more a thought than a must have requests.

In the past, we have had some really important conversations, including one for the multiple passage requests really recently. I think if we open an FAQ page, we should refer to them ( #149 ) or actually have a label for that. We could then, after closing an issue, have someone propose given issue as an important issue. 

You could also have a report for each of these important issues but I think we do not have the time for that.

**Comment by jonathanrobie** [comment]
In W3C specs, change logs refer to the issues that were resolved since the last draft so people can read about what changed.

**Comment by jonathanrobie** [comment]
Should we also add pointers to implementations to the spec?
