### ISSUE TITLE
Discoverability and location of hydra-compliant documentation

### ISSUE THREAD

**Issue by monotasker** [distributed-text-services/specifications#155]
Okay, my work on the crud methods has led me down the rabbit hole of hydra-compliant documentation. So I'll be posting a few issues where you can all explain to me how this works. Then I can document it. I'll be exposing my ignorance here, but I'm hoping the discussion will help us to see how much we need to hold people's hand if we want their implementations to be Hydra-compliant.

First, discoverability of the documentation. The Hydra docs recommend that requests to a site's base URL (www.example.com) include a Link header like this: 

```html
<http://api.example.com/doc/>; rel="http://www.w3.org/ns/hydra/core#apiDocumentation"
```
They also seem to recommend including the same Link header to all responses at api endpoints. I've already added a Link header pointing to docs in the crud method documentation I just merged. (I need to fix it there to use a link entity and include the "rel".) I don't see any downside to including this as a requirement in responses from all endpoints (including the entry point). Any disagreements?

If we're agreed on adding the Link reference to docs, then the next question is whether we want to recommend a location where the hydra-compliant docs are accessible. Should we add a "doc" endpoint to DTS? 

I would definitely suggest we write a separate section of documentation detailing how such docs should be structured. If we send people to the Hydra docs we'll lose a lot of them.

**Comment by PonteIneptique** [comment]
No disagreement at all. 
I don't think we should recommend a location, but generally enough, people would take the example in the header ;)
Agreed on the separate section.

**Comment by balmas** [comment]
+1

**Comment by PonteIneptique** [comment]
During the RC Workshop in Duke, and given the current situation of Hydra, it has been decided to move away from their vocabulary, while acknowledging our inspiration from it.
As a consequence, this issue does not stand anymore.
