### ISSUE TITLE
Structure of hydra-compliant docs

### ISSUE THREAD

**Issue by monotasker** [distributed-text-services/specifications#156]
I'd like to suggest we provide guidance in the docs about how to write the hydra-compliant JSON-LD documentation for an implementation. Much of this should be standard for all implementations, and where we can't just establish boilerplate DTS code I think it would be good to explain for people how to structure a compliant object. But I'm having trouble with some of the details. So can we work together here to draft a sample ApiDocumentation object for www.example.com?

Here's my first stab:
```json
{
  "@context": {
    "@vocab": "http://www.w3.org/ns/hydra/context.jsonld",
    "dts": "https://w3id.org/dts/api#"
  },
  "@id": "http://api.example.com/dts/doc/",
  "@type": "ApiDocumentation",
  "title": "Name of My DTS Implementation",
  "description": "A short description of my API that implements the DTS guidelines.",
  "entrypoint": "https://api.example.com",
  "supportedClass": [ ],
  "possibleStatus": [ ]
}
```

Now, the "supportedOperation" property has to be specified separately for each endpoint. But I can't for the life of me figure out how endpoints are specified in the ApiDocumentation object. The best I can tell, each endpoint should be represented by a hydra Link object. But where do I put those in the ApiDocumentation object so that their role as endpoints is semantically clear? There doesn't seem to be anything like an "endpoint" property. Help is greatly appreciated!

**Comment by PonteIneptique** [comment]
Ok, to help, here is the doc of the demo API for Hydra : http://www.markus-lanthaler.com/hydra/api-demo/vocab

**Comment by PonteIneptique** [comment]
In the DTS Spec history, this relates to 
- https://github.com/distributed-text-services/specifications/issues/144
- https://github.com/distributed-text-services/specifications/issues/139

**Comment by PonteIneptique** [comment]
Now that I have layed out the ground (Is that the correct way to use that ?), my feeling is that we should definitely define most of it, this should also help going towards an API not using prefixes, which IMO should make the adoption easier for people not knowing RDF and related stuff.

I can foresee one difficulty though : the Document endpoint. Maybe we could send an email to the Hydra people and see how to deal with an endpoint containing XML-TEI and not RDF data, but as much as I can understand, I fear this will be difficult.

For the rest, things should be "straight forward": only supportedOperations seems to be "GET", property should most of the time be simple to recopy, although this might led to redefine class for Citation, DublinCore, Extended ?

**Comment by PonteIneptique** [comment]
During the RC Workshop in Duke, and given the current situation of Hydra, it has been decided to move away from their vocabulary, while acknowledging our inspiration from it.
As a consequence, this issue does not stand anymore.
