### ISSUE TITLE
Support versioning of resources 

### ISSUE THREAD

**Issue by balmas** [distributed-text-services/specifications#161]
Requested by @PietroLiuzzo (and others)

The DTS API should explicitly support a way to identify prior and/or alternative versions of a resource.  

@PietroLiuzzo suggests the following approach:

We base our permalinks (https://betamasaheft.eu/pid.html) on the GitHub assigned SHA. I wanted to use the same system used to offer this on our website also for users of the DTS API, so I have added an array of values for dc:hasVersion, which you can see on any response, e.g. 
References and structure change over time, and so I thought it would be useful to refer to previous versions. The API structure is the same, it just looks at the file at that point in its version history.

https://betamasaheft.eu/api/dts/navigation?id=urn:dts:betmas:LIT1367Exodus?level=1   

Where you find a link to this version, where the ref are less
https://betamasaheft.eu/permanent/7361041aa4cf766114ddd593ffc78356660c5db0/api/dts/navigation?id=urn:dts:betmas:LIT1367Exodus?level=1 

I

**Comment by awagner-mainz** [comment]
Have you (in particular @PietroLiuzzo, since you have decided for an approach already) considered using/suggesting users to rely on the [Memento protocol](http://mementoweb.org/about/)?

I have been thinking about integrating permalinks, granularity and versioning for a while (still no clear conclusion), and Memento seems to me like a strong contender for the respective subtask.

**Comment by PietroLiuzzo** [comment]
Thanks!

No, I had not consider it, but I will look at what Memento is now. For us the GitHub versions of a resource are the only meaningful ones, so it seamed sensible to rely on that.

**Comment by balmas** [comment]
Per 11-Oct-2019 Technical Committee meeting
@PonteIneptique 

Recommend putting the versions as children collections of the one you are exposing as the current version, and use DC:isVersionOf

**Comment by PonteIneptique** [comment]
Recommandation to be implemented in doc if people agree: 


```json
{
   "@context":{
      "@vocab":"https://www.w3.org/ns/hydra/core#",
      "dc":"http://purl.org/dc/terms/",
      "dts":"https://w3id.org/dts/api#"
   },
   "@id":"https://digitallatin.org/ids/Calpurnius_Siculus-Bucolica",
   "@type":"Resource",
   "title":"Bucolica",
   "totalItems":5,
   "dts:passage":"/api/dts/documents?id=https://digitallatin.org/ids/Calpurnius_Siculus-Bucolica",
   "dts:references":"/api/dts/navigation?id=https://digitallatin.org/ids/Calpurnius_Siculus-Bucolica",
   "members":[
      {
         "@id":"https://digitallatin.org/ids/Calpurnius_Siculus-Bucolica_0123ef",
         "@type":"Collection",
         "dts:download":"https://digitallatin.org/ids/Calpurnius_Siculus-Bucolica_0123ef/xml",
         "dts:dublincore":{
            "dc:isVersionOf":"https://digitallatin.org/ids/Calpurnius_Siculus-Bucolica"
         }
      },
      {
         "@id":"https://digitallatin.org/ids/Calpurnius_Siculus-Bucolica_ff0000",
         "@type":"Collection",
         "dts:download":"https://digitallatin.org/ids/Calpurnius_Siculus-Bucolica_ff0000/xml",
         "dts:dublincore":{
            "dc:isVersionOf":"https://digitallatin.org/ids/Calpurnius_Siculus-Bucolica"
         }
      },
      {
         "@id":"https://digitallatin.org/ids/Calpurnius_Siculus-Bucolica_ffffff",
         "@type":"Collection",
         "dts:download":"https://digitallatin.org/ids/Calpurnius_Siculus-Bucolica_ffffff/xml",
         "dts:dublincore":{
            "dc:isVersionOf":"https://digitallatin.org/ids/Calpurnius_Siculus-Bucolica"
         }
      },
      {
         "@id":"https://digitallatin.org/ids/Calpurnius_Siculus-Bucolica_aa256f",
         "@type":"Collection",
         "dts:download":"https://digitallatin.org/ids/Calpurnius_Siculus-Bucolica_aa256f/xml",
         "dts:dublincore":{
            "dc:isVersionOf":"https://digitallatin.org/ids/Calpurnius_Siculus-Bucolica"
         }
      },
      {
         "@id":"https://digitallatin.org/ids/Calpurnius_Siculus-Bucolica_ef0123",
         "@type":"Collection",
         "dts:download":"https://digitallatin.org/ids/Calpurnius_Siculus-Bucolica_ef0123/xml",
         "dts:dublincore":{
            "dc:isVersionOf":"https://digitallatin.org/ids/Calpurnius_Siculus-Bucolica"
         }
      }
   ]
}
```

**Comment by balmas** [comment]
my concern about this approach is that it would require drilling down into a collections members to find out if it is a list of prior versions or some other sort of collection.

**Comment by hcayless** [comment]
I don't like it, I'm afraid. For one thing, this is sort of "FRBR-versioning"—they're all instances of a single abstract(?) thing. There's also no order to the versions, which strikes me as a real problem.

**Comment by jonathanrobie** [comment]
What are the requirements for versioning?  What are the use cases?

Is versioning of a complete document sufficient?  Will all projects have the same notion of what a version is?  Should all versions be considered in terms of reverse deltas?

Project level versioning (show me each change between two closely related versions, with the name of the person who changed it) versus publication level versioning ...

One simple approach is to add a version query parameter and a property:

?version=12332352
"version" : "12332352"

**Comment by architexte** [comment]
It has to remain a very simple bibliographical issue: citability of the resource consulted -> find a way to declare a Zenodo or Github version for each passage?
Managing navigation between successive versions is an unnecessary headache.

**Comment by PietroLiuzzo** [comment]
i like the version query parameter option with versions ordered, (and perhaps dated?).
I would have https://betamasaheft.eu/api/dts/navigation?id=urn:dts:betmas:LIT1367Exodus?level=1&version=eed5e03b3ec15ceb77934696194fbd8619c8389e instead of /permanent/eed5e03b3ec15ceb77934696194fbd8619c8389e/api/dts/navigation?id=urn:dts:betmas:LIT1367Exodus?level=1
for dc:isVersionOf, you mean, if I am looking at a specific version, I should have also this property to link to the non versioned id?

**Comment by PonteIneptique** [comment]
We decided that this would be too complicate to support at the API level. If the data provider want to provide different version of the same object, we recommend using multiple resource with `dublincore` use for describing the history of a document.
