### ISSUE TITLE
Ability to declare range capacities

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#164]
Right now, while range is optional, there is no way to advertise for this capacity in the Navigation endpoint. I would propose to note this capacity, either in the reference object model (via a dts:rangeCapacity=True) or via the header (dts-rangeCapacity: yes).

**Comment by balmas** [comment]
agree.

**Comment by mromanello** [comment]
makes sense. This way a client application can raise an exception if a range is requested from an endpoint which does not support it, for example, right?

**Comment by PietroLiuzzo** [comment]
ok

**Comment by architexte** [comment]
Agree, and I have the feeling it has to be declared in the object model. To be discussed…

**Comment by PonteIneptique** [comment]
As per the Action items proposed to me, I would propose to have the following object available in the navigation endpoint (extension to the collection endpoint is not to be excluded):

```json
{
    "@context": {
        "@vocab": "https://www.w3.org/ns/hydra/core#",
        "dc": "http://purl.org/dc/terms/",
        "dts": "https://w3id.org/dts/api#"
    },
    "@id":"/api/dts/navigation/?id=urn:cts:greekLit:tlg0012.tlg001.opp-grc",
    "dts:citeDepth" : 2,
    "dts:level": 1,
    "member": [
      {"ref": "1"},
      {"ref": "2"},
      {"ref": "3"}
    ],
    "dts:passage": "/dts/api/documents/?id=urn:cts:greekLit:tlg0012.tlg001.opp-grc{&ref}{&start}{&end}",
    "dts:capacities": {
        "dts:referenceRange": false
    }
}
```
The property name referenceRange is not perfect, although it is precise.

**Comment by balmas** [comment]
What about 

canReferenceRange 

?

**Comment by PonteIneptique** [comment]
During the RC Workshop in Duke, Conformance was defined as the things that could be done with a static server, and things which could not.

The range capacity is not mandatory for level 0 (conformance with static implementation), but is for level 1.

A section for conformance has been provided in https://github.com/distributed-text-services/specifications/commit/4fb97f2d8402d56f6c81cd06cfc02c7c66c3bd45
