### ISSUE TITLE
Use Case L3: query if a specific version is available

### ISSUE THREAD

**Issue by jonathanrobie** [distributed-text-services/specifications#17]
https://github.com/distributed-text-services/API/blob/master/userstories.csv#L3
- how is a specific version identified?  (CTS Version = edition or translation, the name 'version' is unfortunate)
- how do I learn what versions are available?
- do I need a way to know what versions precede or follow a given version?

**Comment by jeffreycwitt** [comment]
I would want to be able to start with a particular CTS Work in mind and then receive a list of all available CTS Versions. 

But as you rightly note, "Versions" is very ambiguous. What I would want is a list of all possible FRBR Manifestations of this FRBR Expression of this CTS/FRBR Work. 

As a consuming client, I would also want to know what CTS Version / or FRBR Manifestation to default to and which canonicalTranscription to default to.

So something like: 

* hasCanonicalManifestation --> 1985 Edition
* hasCanonicalTranscription --> <the identifier for the privileged transcription of the 1985 edition> (from here I can request the TEIdoc, plainText, or Html)

**Comment by PonteIneptique** [comment]
For cleaning reason, we are closing old issues.
Please feel free to comment if you think we should reopen.
