### ISSUE TITLE
navigation api, going up?

### ISSUE THREAD

**Issue by PietroLiuzzo** [distributed-text-services/specifications#186]
Sorry, I am failing to find an easy way to navigate upwards in the navigation API. I am sure this has been discussed before, apologies for that.
let's say I am starting from an imaginary
 /api/dts/navigation/?id=urn:cts:greekLit:tlg0012.tlg001.opp-grc&level=2&ref=3
what should I use from the response to go to level=1 ? I could use dts:level and dts:citationDepth, but I do feel I would like to have here a dts:parent or a nav parameter like in collection API, and eventually next and prev like in document API.
Thanks a lot!

**Comment by PonteIneptique** [comment]
So, do not worry @PietroLiuzzo, it does seems we had a small oversight there.

**Reason(s) why it should be possible**
It's a feature we have for the <kbd>collection</kbd> endpoint (`?&nav=parents`) and it's an information we provide on the <kbd>document</kbd> endpoint through the `Link` header and the `up` relation: `Link: <ParentDocumentNodeURI>; rel="up"`

**Proposal for fixing this**

1. Add `dts:totalParents` as well as `dts:totalChildren` properties to match the <kbd>collection</kbd> behavior
2. Add a `?nav` URI argument (default to `children`, other value: `parents`)

**Questions that must be raised in a discussion**
1.It is not clear to me whether we can have multiple `Link:<URI>; rel="up"` and if it makes sense to design <kbd>Navigation</kbd> objects as Graph elements which can have multiple parents, the same way we did for `Collection`. If it does make sense, we might and we can't have multiple `rel="up"`, then we have an issue in our <kbd>Document</kbd> specs.
2. If one <kbd>Navigation</kbd> object can only have one parent, I would probably recommend for having a directly reference to the object in the <kbd>Navigation</kbd> object, such as `"dts:parent": {"start": "___", "end": "__"}` or `{"ref": "__"}`

**Comment by hcayless** [comment]
Hi @PietroLiuzzo, we discussed this today and have some questions. With your example, `/api/dts/navigation/?id=urn:cts:greekLit:tlg0012.tlg001.opp-grc&level=2&ref=3` I'm not really sure what you're getting at. If we assume, e.g. that "3" is Book 3 and it contains poems that contain lines, then a query like this should give you the list of poems in book 3. Something like (oversimplified) `[3.1, 3.2, 3.3, 3.4, 3.5]`. Right? So what do you want to know? The list of books available in the document? You'd get that by dropping the `ref=3` parameter and asking for `level=1`.

Or are you really asking, given a reference like `3.2`, how do I know what the level above it is? It's probably `3` of course, but it might not be. We can imagine a situation where all the structural elements in a document have random identifiers, and the parent reference of `id4e85faec-1132-4b14-8184-034626d01e37` is `idc749deee-173c-4c36-88ac-99b12c69b466`. That could be resolved by adding something like a `dts:parentRef` property, which would be a useful and straightforward solution, I think.

**Comment by PonteIneptique** [comment]
Bumping @PietroLiuzzo as we are probably gonna address this again this friday :)

**Comment by PietroLiuzzo** [comment]
Sorry for having managed to be so unclear.
I think I would simply like to have that piece of information in the response explicitly, because 
- it may not be 3 or a number
- my texts are incomplete, it may be missing

For example, I have stuff ordered by Month, Day, Commemoration (besides being organised by folio, page and columns). 
If at level 3 I have a list of commemorations, I would like to know right there in the response what the parent of each is, for example that parent of the passage shown is ref="day3" without having to parse the current ref in the request.  

If `dts:parent` or `dts:parentRef` I am not sure, but I do like dts:parent more because it is already used in collection, and it feels to me like it is really the same thing. I just want to go one level up. 

I do not think I have been careful enough about the `Link: <ParentDocumentNodeURI>; rel="up"` I have to check

**Comment by monotasker** [comment]
This has now been resolved, pending final merge of PR #192
