### ISSUE TITLE
DTS poster at Linked Pasts 6

### ISSUE THREAD

**Issue by mromanello** [distributed-text-services/specifications#190]
I've put together an abstract for a poster submission for the [LP6 conference](https://ics.sas.ac.uk/events/linked-pasts-6) (online), deadline today (November 9, 2020). As I was planning to attend the conference anyway (to some extent), I thought why not presenting DTS there, as it totally fits and it's highly relevant for the community.

**Abstract**

In this poster I will present the [Distributed Text Service API Specification](https://w3id.org/), a community-built effort to facilitate the publication and consumption of texts and their structures in a way that adheres to both FAIR and Linked Data principles. DTS was designed to be as generic as possible, providing simple operations for navigating collections, navigating within a text and retrieving textual content, by means of a fully RESTful API. As it strives for genericity, DTS allows for using any identifier scheme for collections, texts and passages of text, as long as the identifier can be expressed safely as a URL parameter (including e.g. [CTS URNs](http://cite-architecture.org/ctsurn/)). DTS API uses [JSON-LD](https://json-ld.org/) as the serialization format for non-textual data (e.g. descriptive metadata) and [TEI XML](https://tei-c.org/) as the minimum required format for textual data served by the API. In this presentation, I will provide an overview of the operations supported by the DTS API, with examples taken from real-world implementations.

**Comment by balmas** [comment]
that's great. thanks @mromanello

**Comment by hcayless** [comment]
Good idea @mromanello !

**Comment by mromanello** [comment]
thanks, abstract submitted!

**Comment by mromanello** [comment]
quick update: the poster was accepted, and it's due Sunday 29 November. 
I'll try to have a draft ready at some point next week so that you can have a look (and give some feedback) before it's finalised. Here the guidelines for preparation they gave:

> We will make the posters available online for the whole duration of the Linked Pasts 6 symposium, so, please be sure that they are freestanding and self explanatory. The format we require is an A4 PDF, landscape oriented, with any written text not smaller than 12pt.

and also

> We understand that preparing a poster for the screen is not the same as preparing one for printing. We thought that a high quality (ideally 600 dpi) landscape A4 could be a good choice. If you'd rather produce a larger version, just scale everything accordingly (for example, a 300dpi A3 and so on) as it won't be practical for the viewers to look at very large digital files, especially if they are using a small laptop or a tablet. The posters will be uploaded in a gallery, so please, do use a landscape orientation.

**Comment by PonteIneptique** [comment]
Feel free to ask for our feedback, Mr Ambassador :+1:

**Comment by mromanello** [comment]
@PonteIneptique I will for sure. Working on it today (alas the rest of the week was crazy packed). Will ping you (and the others) by email as soon as I have a shareable draft.

**Comment by mromanello** [comment]
Poster PDF deposited hier https://doi.org/10.5281/zenodo.4309361 I think the ticket can be closed ;-)
