### ISSUE TITLE
Should ranger request on Navigation retrieve Reference or a new object ?

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#194]
## Current situation
Currently, on the Navigation endpoint, we have the ability to request ranges, so that `/api/dts/navigation/?id=urn:cts:latinLit:phi1294.phi001.perseus-lat2&ref=1&level=3&groupSize=2` would group levels by 2 under `ref=1`

```js
{
    ...
    "member": [
      {"dts:start": "1.1.1", "dts:end": "1.1.2"},
      {"dts:start": "1.2.1", "dts:end": "1.2.2"},
    ],
}
```

The way we do, we are making the couple `start/end` the equivalent of the `ref` passage, both being `Reference/CitableUnit` objects (_cf._ issue #184 ).

When we start talking about metadata of ranges, including the simplest one like parents, we can see that there are limits to treating both the same way: we are not gonna be able to express easily their parents, nor can we express simply there metadata. 

## Proposal

I propose that we make an data model difference between the couple start/end and ref by simply making the couple start/end a `Range` object type, which would be built onto two references.

So, when I am requesting `CitableUnit` in a `Range` (what composes this range), I have:

```js
{
  ...
  "start": {"ref" : "1", "parent": nul}, 
  "end": {"ref" : "3", "parent": null}
    "@id":"/api/dts/navigation/?id=urn:cts:greekLit:tlg0012.tlg001.opp-grc&level=1&start=1&end=3",
    "dts:citeDepth" : 2,
    "dts:level": 2,
    "member": [
      {"dts:ref": "1.1"},
      {"dts:ref": "1.2"},
      {"dts:ref": "2.1"},
      {"dts:ref": "2.2"},
      {"dts:ref": "3.1"},
      {"dts:ref": "3.2"},
  ...
} 
```

And when I am requesting `Range`s in a `CitableUnit` I have the worse looking but "better":

```js
{
    ...
    "member": [
      {"dts:start": {"ref": "1.1.1"}, "dts:end": {"ref": "1.1.2"}},
      {"dts:start": {"ref": "1.z.1"}, "dts:end": {"ref": "1.z.2"}},
    ],
}
```

**Comment by PonteIneptique** [comment]
Updated.

**Comment by jonathanrobie** [comment]
I think this is a clean proposal.  In general, you will have partial results only at the start and end.

```
 "member": [
      {"dts:start": {"ref": "1.1.4"}, "dts:end": {"ref": "1.1.7"}},
      {"dts:ref": "1.2"},
      {"dts:ref": "2.1"},
      {"dts:ref": "2.2"},
      {"dts:ref": "3.1"},
      {"dts:ref": "3.2"},
      {"dts:start": {"ref": "3.1.1"}, "dts:end": {"ref": "3.1.2"}}
  ]
```

**Comment by PonteIneptique** [comment]
In the discussion yesterday, we discussed this matter.

We tried many things, but we found many obstacles, including
- Adding parents to Range would make it complicated in the context of a probably future `nav=traversal`.
- Adding parents to Range means more computation effort or could introduce big differences in the way we handle Range vs. Unit.

Because it is still possible to get the parents of two milestones (start and end) by making a request on them, and it would only cost 1 HTTP request per milestone, we decided it was a fair price to pay to avoid more complications down the road.

**Comment by PonteIneptique** [comment]
During the Durham RC workshop, we reworked heavily this part of the specifications.

References are now `CitableUnit` which are defined by a required `identifier` property.
Ranges are basically a couple of `CitableUnit` described by the `Navigation.start` and `Navigation.end` properties.

See the new version to get a clearer list of the effect of what we did in the PR #228
