### ISSUE TITLE
what is best practice for retrieval of metadata for documents

### ISSUE THREAD

**Issue by balmas** [distributed-text-services/specifications#195]
It is a little ambiguous how a client would know whether it should look to the TEI returned from the document endpoint or the collection response for the corresponding document for descriptive metadata for a document, and what to do if it is available in both places.

The spec says (emphasis added):

>There is no limitation as to what can be contained by dts:fragment or what its siblings can be provided they are well formed and valid. The only limiting factor is that dts:fragment should contain the requested textual data. This permits an implementation to return contextual material elsewhere within the root TEI node alongside the requested fragment. *Note, though, that most metadata should be accessed through the collection endpoint instead.*

I'm thinking particularly about the case where a client goes directly to the document endpoint (e.g. if it was passed the URL of a document from a user or other application).  Would it make sense to have a recommended implementation practice of the document endpoint returning a link header with a relation of service-meta that references the url for the document in the collection endpoint if the preferred metadata for a document or fragment can or should be found there rather than within the TEI XML itself?

**Comment by PonteIneptique** [comment]
I am wondering if what you're wanting is covered by the Link Header Collection but it seems the `Link` are not described in the documentation right now.

**Comment by PonteIneptique** [comment]
`Link` is now described
