### ISSUE TITLE
Rename level query parameter on Navigation endpoint

### ISSUE THREAD

**Issue by monotasker** [distributed-text-services/specifications#196]
The "level" query parameter on the Navigation endpoint conflicts in a confusing way with the "dts:level" property of the Navigation response object. Both take a single numeric value, but the meaning of the number differs in each case:
 
- The **"level" query parameter** indicates the depth of the references to be returned ***relative to the request's point of reference***. If, for example, a query has a "ref" parameter of "1.2" and a "level" parameter of "1" then the returned references should be the direct children (one level down) of section "1.2". 
- But the **`dts:level` property** of the response object for that same request would be "3". This is because the `dts:level` property indicates the structural level of the returned references ***relative to  the top of the document's citation tree***. Since the request starts at the second level (ref="1.2") and asks for its children (level="1"), the returned references will be at the third level of the document's citation structure: e.g., [{"dts:ref": "1.2.1"}, {"dts:ref": "1.2.2"}, ...]  

This divergence in the meaning of "level" from query to response is confusing. So **I'm proposing that we rename the "level" parameter to "relativeDepth"**. Although this has the disadvantage of being a bit long for the name of a query parameter, it makes the parameter's semantics clear.

**Comment by PonteIneptique** [comment]
I am all for renaming, wondering what would the best keyword be. `descendants`, `relativeDepth`, `down`, etc.

**Comment by PonteIneptique** [comment]
**Decided in 21/12/03 meeting**: we drop the fact that the `level` query parameter is relative to the `ref` and make it relative to the document, so that `level` query param == `dts:level`

**Comment by jonathanrobie** [comment]
Let's discuss navigation use cases first ...

Jonathan generally navigates one level at a time until he reaches a "level of interest", e.g. a chapter of the Bible, or a definition in a lexicon, then he wants "everything from here on down".

**Comment by PonteIneptique** [comment]
Use case: 
I often want to get a specific level from the root, but only this specific level (to avoid filtering the output). For example, get all poems  (level=X) or get all paragraphs (level=Y)

**Comment by monotasker** [comment]
I might want to know how many columns are in a given manuscript fragment, but doesn't want to know all of the lines in each column

**Comment by PonteIneptique** [comment]
I want to get able to retrieve the neighbours of a citation node, in order to make a comparison ?

**Comment by jonathanrobie** [comment]
Proposed functionality for these use cases - all  relative to the reference identifier in the request:

- one level  (including members)
- deep (all levels from here)
- a specific number of levels

**Comment by jonathanrobie** [comment]
Thibault proposes:

?down=1

Default = 1
Semantics: n = the relative level of the members with respect to the identifier
Allowable values:  positive integers or "max"
0 returns only the object without its members

**Comment by monotasker** [comment]
Addressed by pull request #208
