### ISSUE TITLE
Create a web viewer from select parts of different works in a common corpus

### ISSUE THREAD

**Issue by jeffreycwitt** [distributed-text-services/specifications#2]
- Bob wants to create a web reader that displays and compares critical editions of all introductory chapters of English Novels from 1800-1900. 
  - Is it possible to do this without DTS defining a way to identify part of a work as "introductory chapter"? Bob first needs to find all Expressions/Works that are "introductory chapters", see if there are any critical editions, identify if there are digital transcriptions of these editions, then decide which digital transcriptions he should use, and then retrieve the xml, html, or plaintext.

**Comment by PonteIneptique** [comment]
@jeffreycwitt I think you need to either cut this User Story in multiple ones. Or rephrase the title because to me the title has nothing to do with the API specs. Probably more of a `Identify passage with specific types` user story ?

Proposed line for the CSV : 

```csv
client application,retrieve passage identifiers of the same type, compare different works with same intent/type, search, metadata
```

**Comment by balmas** [comment]
I think this belongs in the passage api. Moving there.

**Comment by PonteIneptique** [comment]
Issue closed for the first publication draft. Possible to reopen if you think this is not addressed.
