### ISSUE TITLE
Redirect from one specific version to a second version of a DTS Text

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#20]
## User story
1. **A curator** want to **offer an alternative to an edition that has been discontinued** to **make the link obvious**
2. **A curator** want to **display in his API a resource that comes from outside** but he does **not want to offer the given resource**
3. **DTS Group** want to **create a centralize catalog** so that **user can browse all available DTS resources**
4. **A user** wants to be **aware of a redirectition** so that **they can update their data identifiers**
## Example of implementation given CTS

For clarity, here is an implementation response **example** : 

``` xml
<ti:work xmlns:ti="http://chs.harvard.edu/xmlns/cts" groupUrn="urn:cts:latinLit:phi1294" urn="urn:cts:latinLit:phi1294.phi002">
    <ti:title xml:lang="eng">Epigrammata</ti:title>

    <ti:edition workUrn="urn:cts:latinLit:phi1294.phi002" urn="urn:cts:latinLit:phi1294.phi002.perseus-lat1">
        <ti:redirect to="urn:cts:latinLit:phi1294.phi002.perseus-lat2">This edition is discontinued since Perseus does not host TEI P4 anymore</ti:redirect>
    </ti:edition>
    <ti:edition workUrn="urn:cts:latinLit:phi1294.phi002" urn="urn:cts:latinLit:phi1294.phi002.papyri-lat1">
        <ti:redirect to="urn:cts:latinLit:phi1294.phi002.papyri-lat1" host="http://papyri.info/api/cts">This edition is offered by Papyri.Info</ti:redirect>
    </ti:edition>
    <ti:edition workUrn="urn:cts:latinLit:phi1294.phi002" urn="urn:cts:latinLit:phi1294.phi002.perseus-lat2">
        <ti:label xml:lang="eng">Epigrammata</ti:label>
        <ti:description xml:lang="eng">M. Valerii Martialis Epigrammaton libri / recognovit W. Heraeus</ti:description>
    </ti:edition>
```
## Requirements
- Offer a redirect metadata field in replies (1 2 3)
- Offer a "no-redirect" flag to make redirection clear to end-user / consuming service

**Comment by balmas** [comment]
@PonteIneptique can this be addressed through the hasRole Collection Capability and the role property on MemberItemMappingMetadata or do you need something more added to support this?

**Comment by PonteIneptique** [comment]
I am not sure. I actually think that ultimately, this would be the sameAs or derivedFrom property, which could be set in metadata. Question is : should it be a main feature of the whole scheme ?

**Comment by PonteIneptique** [comment]
For cleaning reason, we are closing old issues.
Please feel free to comment if you think we should reopen.
