### ISSUE TITLE
verse inscriptions

### ISSUE THREAD

**Issue by PietroLiuzzo** [distributed-text-services/specifications#202]
nailing this down during the DTS Hackaton checkin.
I remember discussing this sometime ago. forgive me if I ask again. 
let's say I have a verse inscription.  e.g. https://igcyr.unibo.it/igcyr/gvcyr001.xml 
I may want to cite verse 1 or line 1. 
how do I list in the navigation endpoint that one can have a ref to one or the other citation structure? and how does the request will define that? ref will be 1 in both cases. at the moment I see that I can either split my collection member in two members one for each citation structure or chose one. 
thanks

**Comment by PonteIneptique** [comment]
DTS having no identifier structure, this would requires to forbid this
character in identifiers.
And in general make implementation of client and server harder. My question
would be : why wouldn't the text provider use line1 and verse1 as
identifier instead :)?

**Comment by PonteIneptique** [comment]
During the RC Workshop in Durham, it was decided to supported multiple citation trees, while having a `silent` default one.

From an object perspective, `CitationTree` are found in the `citationTrees` property of a `Resource` (in the `Collection` and `Navigation` endpoint), which is an Array of `CitationTree` object. `CitationTree` objects contain both a `maxCiteDepth` (which was moved from the `Resource` to the `CitationTree`) and `citeStructure` property an Array of `CiteStructure` objects.

The first `CitationTree` found in the array at the `citationTrees` property is the default one, and must not bear an identifier.

From a query parameter standpoint, `?tree` is used both in `Document` and `Navigation` endpoint. `CitableUnit` may have an identifier that can be found in two different `CitationTree`, but each `CitableUnity` identifier must be unique within a `CitationTree`. 

`?tree` must not be used to access the default `CitationTree`

See #228 for its implementation details and its apparition in the specs.
