### ISSUE TITLE
Navigation Endpoint example 8 difficulty

### ISSUE THREAD

**Issue by hcayless** [distributed-text-services/specifications#209]
The example in https://github.com/distributed-text-services/specifications/blob/master/Navigation-Endpoint.md, "Example 8: Passages grouped by the provider" leads us to question the utility of the groupBy parameter. We (Hugh, Ian, and Jonathan) would like to see a use case for it. Otherwise, consider removing it?

**Comment by PonteIneptique** [comment]
I am honestly fine with dropping it. I think it's a feature from CTS (I'd need to check before the meeting) but it's generally doable with compute on the client side easily while asking for one more thing on the server side.

**Comment by PonteIneptique** [comment]
Decision 22-04-2022: Parameter `groupBy` deprecated. Dropped in next `Draft`.

**Comment by rerouj** [comment]
This use case is still on the specifications (https://distributed-text-services.github.io/specifications/). Has it been definitively removed ?

**Comment by PonteIneptique** [comment]
The specification will be cleaned up next week, as a workshop is happening to finish the draft and clean up such messes.
