### ISSUE TITLE
Should dts:references and dts:passage properties be reconciled with entrypoint

### ISSUE THREAD

**Issue by monotasker** [distributed-text-services/specifications#214]

**Comment by PonteIneptique** [comment]
During the RC Workshop in Durham, it was decided that `navigation`, `document` and `collection` would be the properties for such things, and that they should always be expected to be URI Template according to RFC 6570

Implementation in the specs will be visible in https://github.com/distributed-text-services/specifications/pull/238

**Comment by monotasker** [comment]
We published the resolution of this issue during the tech committee meeting on 2024-03-08

commit https://github.com/distributed-text-services/specifications/commit/a0db8ca0f5b9ef2e208baae7cacd8e2b6108685b
release https://github.com/distributed-text-services/specifications/releases/tag/1-alpha1

This is an alpha release and we are looking for feedback!
