### ISSUE TITLE
Request: version of the specification

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [distributed-text-services/specifications#221]
Hi,

I didn't notice mention of a version number in the specification (i.e. as part of the responses) or in the various reference implementations. I imagine it is still evolving and users would find it useful to consult past versions of the documentations or check which version an implementation supports. Is that something you are planning to add to the specification at some point?

Thanks,

**Comment by PonteIneptique** [comment]
Hi @geoffroy-noel-ddh,
Sorry for the delay :)
We are working toward our draft 2. I think starting draft two, it would be indeed great that we keep some kind of versioning. If all things well, #220 might help in settings things correctly regarding versioning :)

**Comment by geoffroy-noel-ddh** [comment]
Hi, no worry about delay, I'm not expecting prompt replies! I guess the intention would be have the version number as a recommended field in all the json responses?

**Comment by PonteIneptique** [comment]
During the RC Workshop in Durham, it was decided that an `apiVersion` property would be part of the main object in the `Navigation`, `Collection` and `Entry` endpoints.
Implementation in the specs will be visible in #238

**Comment by monotasker** [comment]
We published the resolution of this issue during the tech committee meeting on 2024-03-08. The root JSON-LD objects returned by the `Collection` and `Navigation` endpoints now include a `dtsVersion` property.

commit https://github.com/distributed-text-services/specifications/commit/a0db8ca0f5b9ef2e208baae7cacd8e2b6108685b
release https://github.com/distributed-text-services/specifications/releases/tag/1-alpha1

This is an alpha release and we are looking for feedback!
