### ISSUE TITLE
Question: FAIR but CORS

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [distributed-text-services/specifications#224]
Hi,

I've tried accessing three different API implementations mentioned in your documentation (e.g. Perseids, Epigraphische Datenbank Heidelberg) and all of them seem to block cross-origin requests. Which means that APIs can't be called from a different website or viewer. I thought one idea behind the services was to enable FAIR principles and promote free access to resources across projects (i.e. 'distributed'). I have in mind IIIF where generic viewers can fetch manifests and images across servers and this is a core aspects and benefit of the API. 

Do you know why most example implementations do block third party requests? Is it because there has not been any request so far to view their texts through a different user interface or is on purpose to keep a certain amount of control or exclusivity over their presentation or content?

Thanks

**Comment by geoffroy-noel-ddh** [comment]
I guess one deeper question behind this and others I've just posted is whether DTS was primarily (or originally) designed to support projects internal requirements or, instead, to allow third party applications to freely consume and federate texts with little barriers and minimum assumptions about the structural (e.g. units of navigation) or representational conventions (e.g. different views or rendering over the same text) used by each API implementation. The use case I have in mind for the latter case is a generic viewer which could readily browse collections and display a text meaningfully even if the supplied DTS endpoints is entirely new and previously unknown.

**Comment by PonteIneptique** [comment]
> The reason I ask is because I see DTS as potentially one of the best contributor to addressing the issue of broad web access to legacy digital editions. Which, sadly, very often disappear with the obsolescence of the purpose-built software developed around them for a specific research project.

This was the goal, but keep in mind that each project can implement COR restrictions or use DTS as an internal API if they want, after all, DTS is just a specifications (not ISO but still).

In the case of the project you mentioned, I think it's most likely bugs rather than purposefully preventing use of their API.

**Comment by geoffroy-noel-ddh** [comment]
Thanks, sorry for that. That was me requesting the wrong addresses / parameters and the APIs responding with generic pages that had CORS on them. After fixing that I think only one project had restrictive CORS on its API I think (Alpheios).
