### ISSUE TITLE
Change dublincore property to dublinCore 

### ISSUE THREAD

**Issue by monotasker** [distributed-text-services/specifications#228]
We have used camel case for property names except for the `dublincore` property of the response document schema at the Collections endpoint. This property should be renamed `dublinCore` to conform to a consistent capitalization of property names.

**Comment by PonteIneptique** [comment]
As a wise man said one day:

![13Qe](https://user-images.githubusercontent.com/1929830/198626617-58873053-2e49-48e5-bf19-24a2e495281d.gif)

**Comment by monotasker** [comment]
I just noticed that "dublincore" needs to be changed in the context document too.
