### ISSUE TITLE
Conformance Section

### ISSUE THREAD

**Issue by jonathanrobie** [distributed-text-services/specifications#233]
What is required to say that an implementation conforms to DTS?

Does it need to implement all APIs?  Every part of each API?  If we allow partial implementations, how do they interoperate, clearly indicating what parts of the API are not implemented?

Is there a test suite?

**Comment by mromanello** [comment]
- Over the next weeks I will start implementing a DTS test suite based on pytest and building upon initial work by @monotasker (e.g., the JSON schema for collection objects).
- While working on validation, the question of which 'things' belong to which level of compliance will inevitably be raised (and will have to be addressed). 
- After some reflection, I will start by implementing validation against the current specs version (draft 1), and then add the possibility to validate against the new version once it's ready. 

(With respect to validation of a DTS API, issue #219 contains a very relevant discussion thread).

**Comment by PonteIneptique** [comment]
During the RC Workshop in Duke, Conformance was defined as the things that could be done with a static server, and things which could not.

A section for conformance has been provided in https://github.com/distributed-text-services/specifications/commit/4fb97f2d8402d56f6c81cd06cfc02c7c66c3bd45

**Comment by monotasker** [comment]
We published the resolution of this issue during the tech committee meeting on 2024-03-08
commit https://github.com/distributed-text-services/specifications/commit/a0db8ca0f5b9ef2e208baae7cacd8e2b6108685b
release https://github.com/distributed-text-services/specifications/releases/tag/1-alpha1

This is an alpha release and we are looking for feedback!
