### ISSUE TITLE
specs v2 (draft) : documentation endpoint

### ISSUE THREAD

**Issue by rerouj** [distributed-text-services/specifications#240]
Hi,

I'm working on an implementation of the specs based on the PR [#238] and the [monostaker branch](https://github.com/monotasker/specifications/tree/IanScott-documentationFixes). I just have a question about the new documentation of the document endpoint.

My question is mainly about the dts:wrapper element. If the client is requesting a document with a mediaType parameter set to XML (content-type), the API will respond with a document where a dts:wrapper has been inserted.

The thing is probably obvious, but the documentation doesn’t specify if the document displayed is the original one or a new one with a dedicated header and body.

If the document is indeed the original one, can you confirm that the dts:wrapper is only there for "highlighting" a piece of the document and that the whole surroundings elements (including the tei:front and tei:back elements) should be kept ?

My second question is about the text/html media-type. The implementation of this feature is not mandatory, but in the case where it is made available by an implementation , there is a doubt on how the document is supposed to be transformed and if a client could get a document representation, in this case, as an HTML document. Could you please confirm that the transformation scenario is free and that a client could request a complete document in an alternative media-type form ?

Kind regards

**Comment by monotasker** [comment]
Hi @rerouj. On your first question, if you're returning the *whole document* wrapped in its own top-level `<TEI>` element, then there's no need for the `<dts:wrapper>`. If you're returning a subsection of the document, then the `<dts:wrapper>` element provides a standard container for a document fragment or section that would not have an enclosing `<TEI>` element in the source encoding.

As you note, the specification doesn't provide any recommended structure for response types other than XML. So you're welcome to make other media types available *in addition to* the XML response, and you're free to use whatever encoding convention you like. This lets us provide clients with a reliable format (TEI XML) but also gives implementers flexibility where that encoding doesn't satisfy their needs. (Technically the XML *should* be TEI, but it *must* at least be well-formed.)

**Comment by rerouj** [comment]
Thank you for your answer @monotasker. I just still have a doubt. If I return a subsection of a document, should I keep the elements that are not part of the requested fragment or should I only return the ```<dts:wrapper>``` element, along with the requested content ?

Suppose the following document structure :

```xml
<TEI>
    <teiHeader>...</teiHeader>
    <text>
        <front>...</front>
        <body>...</body>
        <back>...</back>
    </text>
</TEI>
```

Suppose I have one document in my database, a poem. In that document there is 7 verses in the body element (I know that this is not well-formed :)) . Suppose also that there is a very long foreword in the ```<tei:front>``` element and a long afterword in the ```<tei:back>``` element. 

What will happen if I request verse 2 to 6 from this document ? in my opinion, there is two ways to represent the requested fragment to the client: 

**1.** The dts wrapper is inserted inside the ```<body>``` element. The ```<front>```, the ```<back>```
and the unrequested elements are kept and returned with the ```<dts:wrapper>``` element.

url : ```document/?resource=poem&start=2&end=6```

result :
```xml
<TEI>
    <teiHeader>...</teiHeader>
    <text>
        <front>...</front>
        <body>
            <verse n="1"></verse>
            <dts:wrapper>
                <verse n="2"></verse>
                <verse n="3"></verse>
                <verse n="4"></verse>
                <verse n="5"></verse>
                <verse n="6"></verse>
            </dts:wrapper>
            <verse n="7"></verse>
        </body>
        <back>...</back>
    </text>
</TEI>
```

**2.** Or, for the sake of clarity, I can remove the unrequested elements and only return the requested element. Then I will have the following response.

```xml
<TEI>
    <teiHeader>...</teiHeader>
    <text>
        <body>
            <dts:wrapper>
                <verse n="2"></verse>
                <verse n="3"></verse>
                <verse n="4"></verse>
                <verse n="5"></verse>
                <verse n="6"></verse>
            </dts:wrapper>
        </body>
    </text>
</TEI>
```

No ```<tei:front>```, no ```<tei:back>``` or unrequested ```<tei:verse>``` in the response.

What do you recommend ? should I follow scenario 1 or scenario 2 (or neither) ?

**Comment by monotasker** [comment]
The spec requires the approach in your second example. No document content should be returned except the content specified by the query parameters, and all of that content should be included in one `<dts:wrapper>`. That means also leaving out the `<tei:front>` and `<tei:back>` as well as the unrequested `<tei:verse>` elements. The idea here is that 

a. if a client wants the entire document with front and back matter they can request it, and the whole document will be returned (as in example 3 in the spec), and
b. otherwise the endpoint is for efficiently retrieving *subsections* of the document

By only returning the specified parts of the Resource's content, we minimize the size of the response and simplify processing for the client (as when, e.g., a client reader application wants to display a small section in a reader, but is making many such calls as the user moves through the document). By enclosing that extract in a `<dts:wrapper>` element we clarify that what is returned is *not* the complete Resource content.

Is that clearer?

**Comment by rerouj** [comment]
perfectly clear ! thank you again

**Comment by PonteIneptique** [comment]
If I may @rerouj, how would you rewrite the documentation to avoid such qui pro quo later ? :)

**Comment by rerouj** [comment]
Hey @PonteIneptique, thank you for asking.

I think that [this part](https://github.com/monotasker/specifications/blob/IanScott-documentationFixes/Document-Endpoint.md#xmltei-encoding-and-sub-tree-representation) of the documentation could add a few details about the requested TEI document sub-section. 

The doc could specify that the siblings of the ```<dts:wrapper>``` should not contain unrequested textual data.

>There is no limitation as to what can be contained by ```<dts:wrapper>```or if its siblings can be provided as long as they are well-formed and valid. [**Please also note that ```<dts:wrapper>``` siblings should not contain unrequested textual data**].

Then the documentation could add a reminder in the examples. The examples are a bit misleading, specially the examples where we can find a ```<tei:head>``` element before the ```<dts:wrapper>```. This is where I will remind that the ```<tei:head>``` doesn't have unrequested textual data and has be inserted legitimately.

therefore the doc could have, for instance, below the [example 2](https://github.com/monotasker/specifications/blob/IanScott-documentationFixes/Document-Endpoint.md#example-2-retrieve-a-subtree-using-start-and-end) a short note :

> note : the ```<tei:head>``` doesn't have unrequested textual data, and so can be kept as a sibling of the ```<dts:wrapper>``` .

If I may, I believe that the documentation could add a few words on what is a *necessary/unecessary* textual data. I also think that a few technical justifications, like the one provided by @monotasker on his last answer should be inserted somewhere :

> (@monotasker) By only returning the specified parts of the Resource's content, we minimize the size of the response and simplify processing for the client (as when, e.g., a client reader application wants to display a small section in a reader, but is making many such calls as the user moves through the document).

Finaly, I think that the documentation could specify what is inside the teiHeader element. Is it a copy of the original header ? are we allowed to compose a shorter or, even better, a new header with specific description data, for instance about the data provider ? This could be useful because, as you know, teiHeaders can be very... verbose.

Actually, it's not clear if the header is a copy of the original one or a placeholder to provide contextual data about the data provider and the generated document provided by the API. But, if we admit that the teiHeader is not just a copy, I would suggest the following sub-text :

> Implementers are free to add any description data in the ```<tei:teiHeader>``` element. The element can be a copy of the ```<tei:teiHeader>``` that can be found in the complete document, a shorter one or a new header with description data about the data provider and the document generated by the API.

This also could be inserted inside the [XML/TEI encoding and sub-tree representation](https://github.com/monotasker/specifications/blob/IanScott-documentationFixes/Document-Endpoint.md#xmltei-encoding-and-sub-tree-representation) sub-chapter.

My english isn't the finest, but I hope that these little suggestions will help.

**Comment by monotasker** [comment]
@rerouj I just want to flag for you that today we released the alpha1 release candidate for specification v1. So the main branch now includes all of our recent work, as does the published html spec site.
