### ISSUE TITLE
Broken links on the /specifications landing page

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [distributed-text-services/specifications#244]
(Accessed 11/03/2024) The links to the Collection Endpoint and other endpoints return a page not found error.

https://distributed-text-services.github.io/specifications/

![image](https://github.com/distributed-text-services/specifications/assets/3778106/08f51e57-1e02-4b3f-a690-f9cc9d5c2e46)

**Comment by PonteIneptique** [comment]
We need to fix the link in the main page
The old doc is available in the history of git, but I guess we could have a version somewhere in a folder with the old version.

**Comment by PonteIneptique** [comment]
You honestly did not need to argue for that, if someone feels like this is necessary, it means it is.

Check https://distributed-text-services.github.io/specifications/versions/1-draft2/ :)
