### ISSUE TITLE
What is version 1?

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [distributed-text-services/specifications#246]
The new spec has a metadata field to declare the DTS version of the response.

According to the spec and the examples the value is "1".

What does "1" mean? 1-alpha or 1-draft2? If 1-apha introduces breaking changes how can you tell if the response conform with the expectations of the client?

**Comment by PonteIneptique** [comment]
Hi @geoffroy-noel-ddh :)
This is a good point ! It's a mistake from us, we should mark it as 1-alpha, exactly for the reason you mention.

**Comment by geoffroy-noel-ddh** [comment]
Gret thanks. Could that version token be addressable somehow? So someone receiving a response with 1-alpha could look it up on your site or the github repo. That could really help the community keeping track of what's what as you keep releasing new version in the future.

**Comment by PonteIneptique** [comment]
Fixed in the current version, and changed the name of the markdown page including for the current specs: https://distributed-text-services.github.io/specifications/versions/1-alpha/
