### ISSUE TITLE
"Passage" in the Navigation endpoint

### ISSUE THREAD

**Issue by philippepons** [distributed-text-services/specifications#249]
Shouldn't the JSON property "passage" in the Navigation endpoint be renamed to "document"?

**Comment by PonteIneptique** [comment]
Thanks @philippepons :) We will harmonize towards `document`, this is an oversight on our end.

**Comment by PonteIneptique** [comment]
Fixed by #251

**Comment by ingoboerner** [comment]
I was wondering what this renaming means on a conceptual level. 

In diagram of the the jTEI article there is a diagram with an overview of the available endpoints, their general function and the required media type they return (see https://journals.openedition.org/jtei/4352) – https://journals.openedition.org/jtei/docannexe/image/4352/img-2.png 

In the article the functions of the Document(s)  (!) and Navigation endpoint are defined as such:

> The Documents endpoint is intended for the retrieval of **textual content** as identified by a collection identifier, and optionally a reference.

> The Navigation endpoint answers the need to provide an index of available passages for a text when possible. It enables a client to provide browse functionality and also supports complex hierarchies in which each browsable passage may contain distinct passages. These passage resources, which the DTS specification names “References,” can be grouped together in ranges (facilitating, for example, the use case of a text which might be segmented into thousands, or millions, of distinct passages which, for the purpose of browsing, are better off grouped in predefined chunks).

The current pre-alpha specification also includes the term "passage", but lists `Collection`, `Resource`,`CitableUnit` and `CitationTree` as the main objects. The term "Citable Unit" is never mentioned in the jTEI article, but is very prominent in the current specification. 

Is now citable unit an equivalent to the former "passage" and, if the jTEI article would have been revised, the above text could read: "The Navigation endpoint answers the need to provide an index of available "citable units" for a text when possible... ?

**Comment by PonteIneptique** [comment]
`CitableUnit` is a replacement for `Reference` in the schema is answer for sure.

Whether the output of the Document endpoint is a CitableUnit textual representation is another question. I don't think so but I'd like the others point of view.

However, in the pre-alpha version, we somehow had the link towards the Document endpoint being called `passage`, which was clearly a mistake (as all our link bear the names of their endpoint: `collection`, `document`, `navigation`). We cleaned up this part through this PR.

**Comment by ingoboerner** [comment]
Thanks for the quick reply! This already helps a lot
![Image](https://github.com/user-attachments/assets/98e42180-98c4-41b6-ae6c-12a84a4ea7e0)
