### ISSUE TITLE
Collection, navigation and passage properties in the Collection and Navigation Endpoints

### ISSUE THREAD

**Issue by philippepons** [distributed-text-services/specifications#250]
In the **Navigation endpoint**, the 3 properties must be given: 
- *passage* (to be renamed in *document*: see issue https://github.com/distributed-text-services/specifications/issues/249?), 
- *collection* 
- and *navigation*. 

For the **Collection endpoint**, on the other hand, only *document* and *navigation* are expected. Shouldn't we standardize, either by adding *passage* to the **Collection endpoint**, or by removing *navigation* from the **Navigation endpoint**?

**Comment by PonteIneptique** [comment]
Yes, we will make `collection` a required URI template for `Collection` and `Resource` objects

**Comment by PonteIneptique** [comment]
Fixed by #251
