### ISSUE TITLE
Missing `@type` property in Navigation endpoint examples

### ISSUE THREAD

**Issue by mromanello** [distributed-text-services/specifications#252]
The documentation for the `Navigation` object says that the `@type` property is required and describes it as
> The object’s RDF class which must be “Navigation”.

However, all examples of `Navigation` endpoint responses are missing this property. This leads to validation errors against the navigation response [schema](https://github.com/mromanello/DTS-validator/blob/main/schemas/navigation_response.schema.json).

This issues concerns the following specs versions: `unstable`, `1-alpha`.

Once someone from the tech. comm. confirms this, I can make a PR after fixing the examples.

**Comment by monotasker** [comment]
Yes, you're right @mromanello. If you can make a PR that would be great.

**Comment by PonteIneptique** [comment]
I'll do all pr once we merge yours
