### ISSUE TITLE
Property `Navigation.collection`: discrepancy between specs and examples

### ISSUE THREAD

**Issue by mromanello** [distributed-text-services/specifications#253]
TLDR; is it `Navigation.collection` or `Resource.collection`? 

The documentation for the `Resource` object indicates `Resource.collection`: 
<img width="961" alt="Screen Shot 2024-07-12 at 10 40 52" src="https://github.com/user-attachments/assets/49069605-086c-461c-911c-ff7c9f9daea0">
But then, in all examples of the `Navigation` object, it seems to be rather `Navigation.collection`:
<img width="954" alt="Screen Shot 2024-07-12 at 10 42 41" src="https://github.com/user-attachments/assets/836f1b44-3a1b-47e9-8a83-71f1cd5c2df9">

**Comment by monotasker** [comment]
Yeah, that's an error. I can fix it when I get a minute.

**Comment by PonteIneptique** [comment]
I am also not completely happy with the fact that we have passage here and not `document ` given that all other links are named according to the endpoint... :D

**Comment by PonteIneptique** [comment]
I think otherwise this point is addressed via #258

**Comment by PonteIneptique** [comment]
What do you think @monotasker ?

**Comment by monotasker** [comment]
Yeah, I just double checked and PR #258 resolved this as far as the lists of properties go, but I still need to fix the Navigation examples to bring them in line with the new stated property lists for Navigation and Resource.

**Comment by monotasker** [comment]
Resolved
