### ISSUE TITLE
ability to check reference validity without retrieving passage

### ISSUE THREAD

**Issue by balmas** [distributed-text-services/specifications#26]
e.g. a cts isValidReff request

**Comment by PonteIneptique** [comment]
I actually wonder if this would be the place for an OPTIONS http call ?

> 9.2 OPTIONS
> The OPTIONS method represents a request for information about the communication options available on the request/response chain identified by the Request-URI. This method allows the client to determine the options and/or requirements associated with a resource, or the capabilities of a server, without implying a resource action or initiating a resource retrieval.

https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html

**Comment by balmas** [comment]
hmm. yes, probably that makes sense.

**Comment by PonteIneptique** [comment]
For cleaning reason, we are closing old issues.
Please feel free to comment if you think we should reopen.
