### ISSUE TITLE
`CiteStructure` objects can be empty ?

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#261]
The current definition of `CiteStructure` make it so that the following tree is valid:

```json
"citationTrees": [
  {
    "@type": "CitationTree",
    "maxCiteDepth" : 2,
    "citeStructure" : [
      {},
      {},
      {}
    ]
  }
]
```
because both citeStructure and citeType are optional.

Should we make citeType required ?

**Comment by monotasker** [comment]
Yes, that seems like fixing a clear oversight
