### ISSUE TITLE
Study and retrieve quotes in different manuscripts with images

### ISSUE THREAD

**Issue by jeffreycwitt** [distributed-text-services/specifications#3]
- Sara wants to study all instances of John 1:1 in Medieval Sentences Commentaries as they appear in German manuscripts. She would like to see diplomatic transcriptions of each of these quotations. Likewise, she would like to be able to compare these transcriptions to the actual coordinate region of a manuscript facsimile. When the results get too big, she would like to filter these quotations by those that appear only in book 1 distinction 1.
  - To do this it seems to me, Sara would need to start at the "quotationType" then look for all Works/Expressions that contain a quote with this quotationType, then identify all Manifestations of this quotation that have a ManifestationType manuscript and where the RegionType="Germany", then see if there are any diplomatic digital transcriptions available, decide which of the available transcriptions to use, and then retrieve the xml, plaintext, or html of this quotation text. At the same time, she also needs to be able to identify if this Manifestation (ms witness) has any Zones. If so, she needs to be able to retrieve those Zones, the coordinate region, the Canvas on which that Zone falls, and finally the Image and Image service that corresponds to that Canvas. Finally, she needs to be able to Filter these quotations, by asking if this quotation is an Expression Element that falls within an Expression with the ExpressionType="book1-distinction1".

**Comment by PonteIneptique** [comment]
It seems to me this user story is a fit them all user story which is problematic to annotate. It also takes as granted some data model which is not explained nor link here.

**Comment by PonteIneptique** [comment]
Separate comment because of separate purpose : the first comment is about the issue description, this one is about DTS and this user story.

It seems to me that this is not under the scope of DTS : it means we would need to integrate images, zones of images, huge / complex data model that would restrain adoption. To me DTS is about text retranscription. While I do think this is an interesting question, I do not think it should be DTS responsability to implement something that specific.

**Comment by PonteIneptique** [comment]
Issue closed for the first publication draft. Possible to reopen if you think this is not addressed.
