### ISSUE TITLE
Apply agreed up terminology to user stories

### ISSUE THREAD

**Issue by balmas** [distributed-text-services/specifications#31]
we need to do a pass through the user stories to apply the agreed upon DTS terminology where appropriate (i.e. for user stories which reference general concepts, we should use DTS terminology not CTS , and if a user story is CTS-specific, then it should be so stated explicitly.

**Comment by PonteIneptique** [comment]
For cleaning reason, we are closing old issues.
Please feel free to comment if you think we should reopen.
