### ISSUE TITLE
Media types for documents

### ISSUE THREAD

**Issue by jonathanrobie** [distributed-text-services/specifications#33]
What media types do we need to support?  I assume that we need to support at least:
- TEI
- HTML

If we support two, that means we should probably allow ourselves to support any needed media type.

**Comment by jonathanrobie** [comment]
We will need custom media types for things like syntax trees.  These may well not be TEI formats.

**Comment by balmas** [comment]
I think this belongs on the passage api. Closing and moving there.

**Comment by PonteIneptique** [comment]
For cleaning reason, we are closing old issues.
Please feel free to comment if you think we should reopen.
