### ISSUE TITLE
Document metadata

### ISSUE THREAD

**Issue by jonathanrobie** [distributed-text-services/specifications#35]
Do we have document metadata that is distinct from the information found in the headers of the document itself, such as the TEI header?

If yes, how is this reflected in the API?  If I retrieve a document, do I get the metadata and a collection that lets me page through the document?  How are the media types for the collection and the document per se reflected in the API?

If no, how would we query for document metadata?  Does this depend on the media type?

**Comment by jonathanrobie** [comment]
If we do have metadata that is distinct from the media type, I assume it must be extensible.  Perhaps the same authorities that serve as naming authorities for URNs could also define metadata for their documents, e.g.

```json
{ 
   ... standard headers
  
  "papyrii.info"  : {  "key" : "value" }
}
```

Perhaps we need to allow for:

1. Metadata used by all groups
2. Metadata used by a given community
3. Metadata used by a single individual or project

**Comment by balmas** [comment]
I think this belongs on the passage api. Closing and moving there.

**Comment by PonteIneptique** [comment]
For cleaning reason, we are closing old issues.
Please feel free to comment if you think we should reopen.
