### ISSUE TITLE
Retrieve transcriptions of marginal notes

### ISSUE THREAD

**Issue by jeffreycwitt** [distributed-text-services/specifications#4]
- Jane wants to retrieve the text of any marginal notations made in a printed version regarding Act 1 of Shakespeare's Hamlet alongside the text about which the marginal note was made. 
  - To do this, Jane needs to be able to identify a work called Hamlet, see if there are any Items of Manifestations of the Expression "Hamlet" that contain a marginal note. She then needs to look to see if there are any transcriptions of the marginal note. If there are, she needs to be able to decide which one to use, and then access a link to the text as xml, html, or plain. At the same time, she needs to be able to move back to the Item on which the marginal note was made, look for available digital transcriptions, select the transcription to use, and then access the text for this Item, as xml, html, or plaintext.

**Comment by PonteIneptique** [comment]
User story seems to be the same as #2 , *ie* identify passages type.

**Comment by PonteIneptique** [comment]
On another note : part of it seems like a use case for Open Annotation, not for DTS

**Comment by balmas** [comment]
Moving this to the passages api

**Comment by PonteIneptique** [comment]
Issue closed for the first publication draft. Possible to reopen if you think this is not addressed.
