### ISSUE TITLE
Restriction on metadata depth

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#42]
Looking at the implementation of a parser for DTS Collection, I would like to propose a restriction on the JSON schema. Given that `collection` represents a javascript parsed json object from a DTS API:

- `collection["metadata"]` is a namespaced dictionary, according to `collection["@graph"]`
- `collection["metadata"]["prefix:term"]` can be :
   - a literal that cannot be localized (such as int) : `collection["metadata"]["prefix:term"] : 5`
   - a URIRef : `collection["metadata"]["prefix:term"] : "A String"`
   - a list of localized literal : `collection["metadata"]["prefix:term"] : [{"@value": "Literal", "@lang": "eng"}]`
   - a list of URIRef: `collection["metadata"]["prefix:term"] : ["http://wikidata.org/object/Author"]`

While being a little bit restrictive, this path might seem to be required if we want to be able to write parsers that catch any of our implementations. I am happy to see this discussed, augmented, as long as we have a definite list of what can happen and won't drive up to collection["metadata"]["prefix:term"][0]["prefix:term"][0]["prefix:term"][0]["prefix:term"]`

**Comment by balmas** [comment]
At first glance I don't see a problem with this, but I'd like to think about it a bit

**Comment by PonteIneptique** [comment]
@balmas I think this issue has not rise any reaction, maybe we move to last call today ?

**Comment by balmas** [comment]
ok moved to last call.

**Comment by balmas** [comment]
FWIW I'm fine with this proposal

**Comment by balmas** [comment]
we agreed to implement this. passing to PR stage.

**Comment by PonteIneptique** [comment]
Might need to be made clearer in the doc, leaving open

**Comment by PonteIneptique** [comment]
Finally closed by https://github.com/distributed-text-services/specifications/commit/91bbc1cfe071b7a803e74b9dafd699d69a296e0a
