### ISSUE TITLE
Collection should have a description

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#44]
## Proposal

Right now, collection have only label as human readable required information. I would propose to add description as a root property, while not making it mandatory. This would be the equivalent of ttp://purl.org/dc/elements/1.1/description .

## Reason

As I implement a reader for our CTS collections using our new models based on DTS, I thought that a description, even if not mandatory but recommended, would be a great human addition for browsing. This would also federates a little metadata schemes, without enforcing one (you can still have your own namespaced description if will be in .metadata)

## Example
 
```json
{
  "@id": "urn:cts:latinLit:phi1294",
  "label": [{"@lang": "eng", "@value": "Martial"}],
  "description": [{"@lang": "eng", "@value": "Author of the first century who wrote in Latin"}]
}

**Comment by balmas** [comment]
agreed

**Comment by jeffreycwitt** [comment]
What's the distinction between stuff that gets classified as "metadata"?

I put "description"  in the object for the "metadata"

**Comment by PonteIneptique** [comment]
The difference, to me, would be that it is part of the natural scheme of the DTS API instead of a customization of an implementation. It does not mean you need to have it but at least it could be there and is recommanded :)

**Comment by balmas** [comment]
@PonteIneptique is this made obsolete by #51 ?

**Comment by PonteIneptique** [comment]
Only if #51 is accepted

**Comment by PonteIneptique** [comment]
Implemented through dts:dublincore and hydra:description
