### ISSUE TITLE
Why /collections/{id}/metadata?

### ISSUE THREAD

**Issue by hcayless** [distributed-text-services/specifications#45]
Why would we have a separate request URI for collection metadata? Won't metadata be a component of the collection JSON-LD? In a sense, the collection response is nothing *but* metadata, making me wonder whether "metadata" is a sensible member for a collection object. Maybe that should be "other_metadata" or "extra_metadata"?

**Comment by balmas** [comment]
If you have a collection with thousands+ members you might not want to retrieve all of that data just to display information about the collection.  Particularly if the implementation doesn't support pagination via cursors.

**Comment by hcayless** [comment]
So the response will be everything *but* the "members" property? I think we should definitely rename the "metadata" property in that case.

**Comment by PonteIneptique** [comment]
Should we actually have a filter for that, lile "?nomembers" ?

**Comment by balmas** [comment]
hmm. that's not really how I understand filter. I would expect filter to reduce the collections in the response, not the details returned for each.  But that is an interesting concept - if we supported that then I guess we could eliminate the separate api route.

**Comment by PonteIneptique** [comment]
Bad word use but the idea stay the same. Maybe output parameter? :')

Le 16 mars 2017 1:49 PM, "Bridget Almas" <notifications@github.com> a
écrit :

**Comment by jonathanrobie** [comment]
How much metadata do we expect for a collection?  I would expect `/collection{id}` to return the collection's metadata, plus an array containing the first page of children, where each entry contains a small subset of the metadata for each entry - enough to allow a collection to be selected.

I would also expect collections to page.

**Comment by balmas** [comment]
The rationale for a separate metadata request was to support the case where you want only metadata and not the members of a collection.

Collections should page, the `page` parameter is missing from that request in the spec right now, although the response contains pagination information.

**Comment by PonteIneptique** [comment]
For cleaning reason, we are closing old issues. Please feel free to comment if you think we should reopen.
