### ISSUE TITLE
SCTA implementation question - no "http://scta.info/resource/work" ?

### ISSUE THREAD

**Issue by balmas** [distributed-text-services/specifications#46]
Question from Paolo:

I did read Jeffrey's demo files, and there is one thing that's unclear to me: the only "rdf:type"s I find in
http://scta.info/dts?resourceid=http://scta.info/resource/scta
are:

"rdf:type": "http://scta.info/resource/workGroup",
and
"rdf:type":"http://scta.info/resource/expression".

There's no
"rdf:type":"http://scta.info/resource/work".
anywhere. Is this due to a choice made in previous conversations, that I missed, or Jeffrey's decision?

**Comment by jeffreycwitt** [comment]
Paolo, "Work" is in our model, I just haven't implemented yet, as it requires curatorial decisions about the relationships between the texts themselves. 

But in my view "Work" is identical to a WorkGroup with the exception only that Work cannot contain further Works or WorkGroups as children (hasPart), but can only take expressions as children (hasPart).
