### ISSUE TITLE
CTS & SCTA implementations: Namespace question

### ISSUE THREAD

**Issue by balmas** [distributed-text-services/specifications#47]
From @jtauber 

Should `ns1` in the `@context` be `dc`?

**Comment by PonteIneptique** [comment]
Technically, it's only a prefix. So it is not of the upmost importance :) The importance is that prefix are well reused inside the implementation :)

**Comment by jtauber** [comment]
Right, but I raised it because`ns1` is declared (with the DC URL) but not used and the `dc` prefix is used but not declared.

**Comment by jtauber** [comment]
(to be clear, this was in the example Jeff posted in an email which is why I just asked in reply to his email rather than creating an issue yet)

**Comment by balmas** [comment]
Sorry to add confusion by making it an issue, but it's easier for me to stay organized if I keep everything in one place. I did label it question.... :-)

**Comment by jtauber** [comment]
Oh, it's fine as an issue, I'm just clarifying that I first noticed the mismatch in Jeff's email and hadn't gotten around to creating an issue for it yet. Tracking things as issues is good :-)
