### ISSUE TITLE
Ethopic Texts User Story

### ISSUE THREAD

**Issue by balmas** [distributed-text-services/specifications#49]
From @PietroLiuzzo 

We have 1 TEI record for each work which had in the ethiopic tradition an independent circulation, which means for example that we have:

* one record for each of the miracles of mary

* one record for the work "miracles of mary"

while we leave the attestation of each given number and selection of miracles to the manuscripts records which are not in scope here. 

The main record is linked with a relation element to the other records it might contain and we use @name with the a relation in the saws vocabulary to state this relation. 

Another thing is that we have several other types of relations which are not contain-isPartOf, for example for recensions, versions, etc.

A collection in this case would be

* my generic record 

* and would contain members which are possible or certain parts of it with a role corresponding to the named relation

**Comment by PonteIneptique** [comment]
For cleaning reason, we are closing old issues. Please feel free to comment if you think we should reopen.
