### ISSUE TITLE
Retrieve identifiers based on author/textgroup name or by place

### ISSUE THREAD

**Issue by PietroLiuzzo** [distributed-text-services/specifications#5]
https://github.com/distributed-text-services/API/blob/master/userstories.csv#L31 
I want to find out what the editions of a work are. I don't know the canonical id of the work, but I know that of the author. or I don't know that either. I would like to be able to query for a collection and see all the ids. in the case of a collection of inscriptions I would like this to be broken down by provenance.

**Comment by PonteIneptique** [comment]
@PietroLiuzzo I propose the new title : `Retrieve identifiers based on author/textgroup name or by place`

**Comment by PonteIneptique** [comment]
Issue closed for the first publication draft. Possible to reopen if you think this is not addressed.
