### ISSUE TITLE
Metadata main scheme ( CollectionAndMembers ) can have any dc:predicate at the root

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#52]
Right now, we have as required : 

```
0:"@context"
1:"@id"
2:"type"
3:"license"
4:"size"
5:"labels"
6:"vocabulary"
7:"capabilities"
8:"metadata"
9:"members"
```

I would actually propose to have the ability to use every dc original predicates as basic value : 

- Title (Instead of label and so required)
- Creator (Optional)
- Subject (Optional)
- Description (Optional but duplicate of #44 )
- Publisher (Optional)
- Contributor (Optional)
- Date (Optional)
- Type (Required, different from dts:type which would be dts:collection or dts:readableCollection)
- Format (I think this one is not needed, except if we have a dts:type dts:static for image or so)
- Identifier ( == @id so omitted ?)
- Source ( Optional )
- Language ( Required for dts:readableCollection, replies to the need of #51 )
- Relation ( Optional )
- Coverage (Optional)
- Rights (Replies to the license issue I could not find again...)

I think this can be discussed and would be interesting. The good outcome of this would be the 1:1 possible translation to OAI-PMH APIs :)

**Comment by balmas** [comment]
what is dts:readableCollection vs dts:collection? I don't recall seeing this before.

**Comment by PonteIneptique** [comment]
I'll open an issue @balmas . Missing it, I actually used it in MyCapytain

**Comment by balmas** [comment]
I agree with this suggestion.

**Comment by hcayless** [comment]
I agree too.

**Comment by jonathanrobie** [comment]
Me too.

**Comment by PonteIneptique** [comment]
Added with dts:dublincore
