### ISSUE TITLE
Resolving collection affordances

### ISSUE THREAD

**Issue by hcayless** [distributed-text-services/specifications#56]
Was #39 and #54.

After a discussion between myself, @balmas, @PonteIneptique, and @jonathanrobie we are agreed that the collections API should distinguish between collections that contain only metadata (and possibly other collections), collections that permit the download of resources, and collections that have resources whose contents are exposed via the reference and passage APIs. The resolution of this ticket will mean a general agreement that these are properties a collection should have.

**Comment by balmas** [comment]
Just clarifying - "distinguish between" doesn't mean that all of these properties are mutually exclusive. I.e. a collection might both permit the download of resources and have resources whose contents are exposed via the reference and passage APIs.

**Comment by PonteIneptique** [comment]
Fixed by Hydra, dts:download and the likes
