### ISSUE TITLE
Diod. 12.40

### ISSUE THREAD

**Issue by PietroLiuzzo** [distributed-text-services/specifications#6]
https://github.com/distributed-text-services/API/blob/master/userstories.csv#L30
I would like to query for /cts/Diodorus/12.40
and be directed to /cts/greekLit/tlg0060/tlg001/12.40
perhaps also to the "most likely" available text for display and a list of other options (other translations, other editions, etc.)

**Comment by balmas** [comment]
I think this is a requirement for the passages api. Moving it there.

**Comment by PonteIneptique** [comment]
Issue closed for the first publication draft. Possible to reopen if you think this is not addressed.
