### ISSUE TITLE
Use case scenario coverage

### ISSUE THREAD

**Issue by balmas** [distributed-text-services/specifications#61]
Submitted by @jonathanrobie  (moved from github.io project)

Note:  This issue should be used to spawn other issues that are more specific - those other issues should be closed separately.

Some of the [use case scenarios](https://github.com/distributed-text-services/collection-api/blob/master/userstories.csv) are beyond the scope of the current proposal: 

- Annotations
- Revision history

This kind of functionality could be added in a later version, or the proposal could be extended.  How important is it in the first release?

Others are not satisfied - particularly the write operations - but could be with modest effort.

**Comment by PonteIneptique** [comment]
For cleaning reason, we are closing old issues. Please feel free to comment if you think we should reopen.
