### ISSUE TITLE
Use URI parameters to distinguish collections, documents, etc?

### ISSUE THREAD

**Issue by balmas** [distributed-text-services/specifications#67]
_From @jonathanrobie on September 13, 2017 20:2_

Hypermedia REST APIs generally have a single entry point, and clients are not required to parse URIs with the exception of URI parameters that can be provided via URI templates.  We currently have a compromise design that has a small set of entry points: `/collections`, `/documents`, etc.

We could be more RESTful by distinguishing these using URI parameters rather than separate entry points: `/?scope=collections`, `/?scope=documents`, etc.  Should we?

_Copied from original issue: distributed-text-services/distributed-text-services.github.io#8_

**Comment by balmas** [comment]
_From @PonteIneptique on September 14, 2017 7:4_

So, both these issue are a bit short notice, if we have an agreement, then it's perfect, otherwise we might need a little more reflection.

I do not know if we need to be more or less restful. I think this option is something I proposed, to be a little more like CTS, and you rejected it. So I am a little lost.

**Comment by balmas** [comment]
_From @jonathanrobie on September 14, 2017 13:0_

> So, both these issue are a bit short notice, if we have an agreement, then it's perfect, otherwise we might need a little more reflection.

That's how issues work - raising an issue says it's something we need to decide before we are finished.  The group has to decide when it is ready to decide.

**Comment by balmas** [comment]
_From @PonteIneptique on September 14, 2017 13:1_

No worries at all. I would probably ask for a no-issue day the day before the meeting. Ie we can talk in the issues but not create new ones. I think this could be a beneficial code of conduct :)

**Comment by PonteIneptique** [comment]
Should we actually close this issue before draft is out ?

**Comment by PonteIneptique** [comment]
For cleaning reason, we are closing old issues. Please feel free to comment if you think we should reopen.
