### ISSUE TITLE
Get to a standard result

### ISSUE THREAD

**Issue by PietroLiuzzo** [distributed-text-services/specifications#7]
https://github.com/distributed-text-services/API/blob/master/userstories.csv#L29
if I don't specify the edition but I specify the passage I want to get to a standard edition and know about options

**Comment by PonteIneptique** [comment]
This issue could easily be Search / Metadata or Collection or Content. Not sure which one to use here.

**Comment by balmas** [comment]
@PietroLiuzzo Is this the same as #6 ?

**Comment by PonteIneptique** [comment]
Issue closed for the first publication draft. Possible to reopen if you think this is not addressed.

**Comment by PonteIneptique** [comment]
For cleaning reason, we are closing old issues.
Please feel free to comment if you think we should reopen.
