### ISSUE TITLE
Provide a way in Navigation API to go back to the parent from a children

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#76]
Right now, the Collection API states `members` but provides no way to navigate back to parent(s).

Two questions arise here : 
- should our collection be tree-based (one collection = maximum one parent) ?
- how do we state this link ?

@jonathanrobie any input from the Hydra side for this kind of relation ?

**Comment by jonathanrobie** [comment]
I am nervous about things like a bilingual Greek/Latin edition of one of the Church Fathers.  Is it Greek literature?  Latin literature?  Church fathers?  Ideally, I would like it to be in all of these collections.

If we don't want to restrict it to a single collection, but do want to be able to navigate back to a parent, there are at least two possibilities:

1. Leave it up to the client to cache the parent.
2. Let an item contain a list of all collections in which it is contained.  There is a cost in complexity or speed if we do this.

**Comment by PonteIneptique** [comment]
I agree with non limiting. All in all, I think limiting to a single parent in catalog is a bad principle. But we could have the same thing as `member` with `dts:parent` and have only the limited response people can expect (ie what's mandatory : totalItem, id, title, type)

**Comment by balmas** [comment]
Agree we should not limit a document or collection to a single parent.

Offering links back to one or more parent collections from an item could be tricky especially if an implementation wanted to support dynamically created collections. Not sure if this should be a requirement of the API. Maybe it should be implemented (instead or in addition) as a query?

**Comment by PonteIneptique** [comment]
Something like `?include=parent` and a `dts:parent` ?

**Comment by balmas** [comment]
yes something like that :-)

**Comment by jonathanrobie** [comment]
In today's call, we agreed on the following:

1. No parent in the response format
2. Need a way to query for all parents of a given resource
3. CTS can use identifiers to identify a parent

Justification: doing this right with multiple collection types is complex and requires a lot of the implementations, and a query will do.

**Comment by jonathanrobie** [comment]
I suggest we use a query parameter named something like `nav`, e.g.

`resourceuri?nav=parent`

We could allow values like these:

- parent
- children
- prev
- next

**Comment by PonteIneptique** [comment]
I am adding a note here for the moment : ordered collection was kept back at a moment, I believe we should keep it that way (so only parent and children would make sense at the moment)

**Comment by PonteIneptique** [comment]
Dealt with in @334170607af23fdf7e55d9dbc55e5d23b0a744ed
