### ISSUE TITLE
get any text, not just canonical

### ISSUE THREAD

**Issue by PietroLiuzzo** [distributed-text-services/specifications#8]
https://github.com/distributed-text-services/API/blob/master/userstories.csv#L28

this might be split down, but I am not sure that is already useful for the API

If I query a work like the res gestae divi augusti I would like to be told there are x inscriptions with this work

so, if I query for cts/{work} = cts/resgestaeID I get a list of the available editions, let them be editions of the inscription or as literary work

a simpler case for this would be an inscription with several editions online

**Comment by PonteIneptique** [comment]
@PietroLiuzzo I am not sure to understand this one : do you want inscriptions which are reproduction of the resgestae or inscription that are comment about the res gestae ?

**Comment by PietroLiuzzo** [comment]
I believe this is already addressed as I can get an abstractWork, or exemplars or editions

**Comment by PonteIneptique** [comment]
For cleaning reason, we are closing old issues.
Please feel free to comment if you think we should reopen.
