### ISSUE TITLE
Retrieve title of passages along references

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#80]
**This issue is not important for the first draft**

When discussing with @architexte, it became clear that, on top of retrieving typologies of passage, there is text providers that would be interested in providing passage titles as they provide the identifier of those, for building resources like *Table of Contents*.

In the world of classical texts, this might not make much sense, but in the world of more modern texts, most of all contemporaneous non literature texts, it does.

This means : 
- We need to agree on this being a DTS feature 
- we need a parameter name (`label` ?)
- we need a response *field*

**Comment by architexte** [comment]
Of course (it's my request) I agree with @PonteIneptique. One could argue that this need is up to the implementer, but for modern texts it is almost mandatory (eg get/display the title of a poetry).
The parameter name could be `label` or `heading`.

**Comment by hcayless** [comment]
There may be cases even in ancient works where this is desirable. I'm in favor.

**Comment by jonathanrobie** [comment]
I like the functionality, but I would prefer not to complicate the API by special-casing a given element.  There are two routes that make sense to me:

- Let the document drive - if there is a subtitle, return it, or
- Provide a "view" query parameter that allows you to specify which fields are returned.

**Comment by jonathanrobie** [comment]
We agreed to let the document drive in the first release.  Views could be done in a later release.

**Comment by PonteIneptique** [comment]
Closed in #118
