### ISSUE TITLE
Response format for missing parameters

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#85]
Something that we oversaw : we did not define common error messages, response format and codes for : 

- [ ] Missing parameter
- [ ] Unknown document
- [ ] Unavailable parameter

I think it would be great to add these !

**Comment by hcayless** [comment]
Agreed. I think:
 * Missing parameter: 400 Bad Request
 * Unknown document: 404 Not Found
 * Unavailable parameter: (either 400 or 501 Not Implemented)

Response format is a good question. Usually JSON, I suppose, but for request types that expect XML, maybe we need a `<dts:error>` tag?

**Comment by PonteIneptique** [comment]
Hmm. I did not think of the XML option as well but I see why you're thinking about it.

So : 

```json
{
  "error": "MissingParameter"
  "message": "The request you made was missing a parameter"
}
```

```json
{
  "error": "UnavailableParameter"
  "message": "The request you made was using a parameter that is not available in this context"
}
```

```json
{
  "error": "UnknownIdentifier"
  "message": "The document %IDM was not found."
}
```

and the equivalent

```xml
<error xmlns="dts namespace..." type="UnknownIdentifier" message="The document %id% was not found" />
```

Should the message and types of error be a "controlled vocabulary" (not in the ontology sense but rather a list of valid sentences/types)

**Comment by hcayless** [comment]
```xml
<error statusCode="429">
  <title>Too Many Requests</title>
  <description>A maximum of 500 requests per hour and user is allowed.</description>
</error>
```
?

**Comment by jonathanrobie** [comment]
Agreed: We will use Hydra for all endpoints except Document.

For Document we will accept Hugh's proposal.

**Comment by PonteIneptique** [comment]
Closed by https://github.com/distributed-text-services/specifications/commit/eb3e45ff35c1150d9add75b62590129a3f4450fb
