### ISSUE TITLE
What is the influence of `?nav` parameter over `totalItems` values ?

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#87]
On the collection API, we can request `?nav=children` (which is the default) but also `?nav=parent`. In the Collection API, `totalItems` hydra property is described as `the number of children hold by an object`. 

There is more than one meaning to this property that is possible : 
- It always covers the size of the children direction, even if we are requesting parents (would be weird but I can get along with that).
- It covers the full size of `members` which is computed according to `?nav`; meaning `totalItems` == `number of parents` when `?nav=parent`
  - If so, what would be the size of `?nav=prev` or `?nav=next`' `members` ?
  - If so, is the `totalitems` from members computed according to the route `?nav` parameters ? It would mean that when I request `?nav=parent`, `collection["members"][0]["totalItems"]` is the number of parents for the first list member of the requested collection ?

If this is it, I would advocate for a `dts:size` property that would be required and always displays the number of children, regardless of `?nav`

**Comment by PonteIneptique** [comment]
(If it's not clear enough, feel free to reformulate and I'll say if this is what I meant :D )

**Comment by jonathanrobie** [comment]
I think the answer to this is straightforward.

See this edit:

https://github.com/distributed-text-services/specifications/commit/a1854d8c89fa1764dadd08771496476790fc138e

TotalItems is simply the number of items in the resulting collection.

**Comment by PonteIneptique** [comment]
`nav` applies to current collection and its members.
