### ISSUE TITLE
skipping directly to text for inscriptions or papyri 

### ISSUE THREAD

**Issue by PietroLiuzzo** [distributed-text-services/specifications#9]
if I ask dts/tm203114
I get links to all the online resources which refer to this
HD059795
EDCS-06000984
IRT957

I guess this would be something like dts/{text}

**Comment by PonteIneptique** [comment]
@PietroLiuzzo I have two understanding, could you tell me which one is the good one : 

- (Current I annotated with : Search, ID) I want to be able to ask for one identifier and be given other known resources identifier and exemplar online.
- (Read, Content) I want to be able to use different identifier but still be redirected to the same resource.

**Comment by PietroLiuzzo** [comment]
first one. if TM is AbstracWork, the others would be exemplars of it. each can also resolve to a textObject.

**Comment by PonteIneptique** [comment]
For cleaning reason, we are closing old issues.
Please feel free to comment if you think we should reopen.
