### ISSUE TITLE
should start always require end and vice-versa?

### ISSUE THREAD

**Issue by balmas** [distributed-text-services/specifications#91]
do we want the spec to declare whether `start` always requires `end` and vice-versa?

**Comment by PonteIneptique** [comment]
I honnestly think we do. Developer might want to cover for that if they want but I'd say we do required `end` and `start` together

**Comment by emmamorlock** [comment]
+1

**Comment by PonteIneptique** [comment]
During the Durham RC workshop, we clarified the combination of `?ref`, `?start` and `?end` in terms of error they can throw.

`?start` and `?end` must be used together.
`?ref` must not be used with either `?start`, `?end` nor both.

See the new version to get a clearer list of the effect of what we did in the PR #228
